import {createComponent,createGlassSystem,bindControlSounds,bindKeyboardFocus} from './index.js';
import {mountOpticalDemo} from './optical-demo.js';
import {componentCatalog} from './component-catalog.js';
const unbindFocus=bindKeyboardFocus(document);
const catalogCopy={
 zh:{showcase:'完整展示',components:'组件',tokens:'设计变量',extend:'接入与扩展',title:'Lens 设计系统',intro:'厚润材质、弹性手势与轻声反馈，共用同一套规则。',live:'真实交互组件',example:'打开独立接入示例',finish:'材质',thick:'厚润',clear:'通透',soft:'柔和',scene:'背景',aurora:'流光',ocean:'深海',grid:'光学网格',sounds:'交互音效',volume:'音量',tokensTitle:'统一变量，保留个性',tokensIntro:'共享变量来自 tokens.js，并生成 CSS 与 JSON。页面可覆盖 CSS 变量；材质参数、声音和组件都可独立扩展。',layer:'层级',source:'来源',includes:'包含',visual:'视觉',visualDetail:'颜色、字号、间距、圆角、表面与阴影',material:'材质',motion:'动效',motionDetail:'弹性、时长、缓动与减弱动态效果',sound:'声音',soundDetail:'13 种短音效、音量、触发节流和静音',extendTitle:'从一个控件开始',extendIntro:'复制整个 design-system 文件夹即可接入，无运行时依赖。组件用语义化 HTML，渲染和音效在外层统一管理。',api:'API 与扩展指南',rules:'设计规则',tokenFile:'查看 JSON 变量',lab:'返回材质实验室',limit:'折射覆盖画布背景与玻璃层，不会自动捕获任意 DOM。WebGL 不可用时使用 CSS 毛玻璃，音效不可用时保持所有交互。',buttons:'按钮 · 禁用状态',save:'保存此刻',saved:'此刻已保存',disabled:'暂不可用',switch:'专注开关 · 可拖动',choices:'选项胶囊 · 方向键选择',idea:'灵感',work:'工作',life:'生活',slider:'滑杆 · 连续调节',brightness:'亮度',stepper:'步进器 · 明确边界',duration:'时长',unit:'分钟',less:'减少时长',more:'增加时长',search:'搜索框',find:'查找组件',placeholder:'输入内容，听见轻声反馈',notification:'通知 · 收起与恢复',noticeTitle:'给想法一点空间',noticeBody:'从 25 分钟开始，专注眼前。',dismiss:'收起通知',restore:'重新显示',panel:'面板 · 按住拖动',panelText:'共享材质与弹性手势',lens:'透镜 · 自由拖动',lensAria:'透镜位置，使用方向键或拖动移动',lensCaption:'按住，感受流动',ready:'可以点击、拖动，也可以使用键盘。',on:'专注已开启',off:'专注已关闭',soundFallback:'当前浏览器无法播放声音，视觉反馈仍然可用。'},
 en:{showcase:'Full showcase',components:'Components',tokens:'Tokens',extend:'Use & extend',title:'Lens design system',intro:'Thick glass, elastic gestures and quiet sound. One shared foundation.',live:'Live components',example:'Open the independent example',finish:'Finish',thick:'Thick',clear:'Clear',soft:'Soft',scene:'Scene',aurora:'Aurora',ocean:'Ocean',grid:'Optical grid',sounds:'Interaction sounds',volume:'Volume',tokensTitle:'Shared rules. Room to adapt.',tokensIntro:'tokens.js generates the CSS and JSON tokens. Override CSS variables per surface, or extend materials, sounds and components independently.',layer:'Layer',source:'Source',includes:'Includes',visual:'Visual',visualDetail:'Color, type, spacing, radius, surfaces and shadows',material:'Material',motion:'Motion',motionDetail:'Elasticity, duration, easing and reduced motion',sound:'Sound',soundDetail:'13 short cues, volume, rate limiting and mute',extendTitle:'Start with one control.',extendIntro:'Copy the design-system folder. No runtime dependencies. Controls are semantic HTML; the outer system manages rendering, motion and audio.',api:'API & extension guide',rules:'Design rules',tokenFile:'View JSON tokens',lab:'Back to the material lab',limit:'Refraction samples the canvas scene and glass layers, not arbitrary DOM. CSS frosting handles WebGL fallback; audio failure never blocks interaction.',buttons:'Buttons · Disabled state',save:'Save this moment',saved:'Moment saved',disabled:'Unavailable',switch:'Focus switch · Drag to change',choices:'Choice pills · Arrow-key selection',idea:'Ideas',work:'Work',life:'Life',slider:'Slider · Continuous adjustment',brightness:'Brightness',stepper:'Stepper · Clear limits',duration:'Duration',unit:'min',less:'Decrease duration',more:'Increase duration',search:'Search field',find:'Find components',placeholder:'Type to hear quiet feedback',notification:'Notification · Dismiss and restore',noticeTitle:'Make room for an idea.',noticeBody:'Start with 25 minutes. Be here, now.',dismiss:'Dismiss notification',restore:'Show notification',panel:'Panel · Hold to drag',panelText:'Shared material and elastic gestures',lens:'Lens · Free movement',lensAria:'Lens position. Drag or use arrow keys.',lensCaption:'Hold to feel it flow',ready:'Click, drag, or use the keyboard.',on:'Focus is on',off:'Focus is off',soundFallback:'Audio is unavailable in this browser. Visual feedback remains available.'}
};
const qs=selector=>document.querySelector(selector),stage=qs('#catalog-stage'),samples=qs('#catalog-samples');
const catalogCardIcon=()=>{const svg=document.createElementNS('http://www.w3.org/2000/svg','svg');svg.setAttribute('viewBox','0 0 48 48');svg.setAttribute('aria-hidden','true');svg.style.cssText='display:block;width:48px;height:48px';const square=document.createElementNS(svg.namespaceURI,'rect'),mark=document.createElementNS(svg.namespaceURI,'path');for(const [name,value] of Object.entries({x:4,y:4,width:40,height:40,rx:11,fill:'#72C9B5'}))square.setAttribute(name,value);for(const [name,value] of Object.entries({d:'M14 17h20M14 24h14M14 31h17',fill:'none',stroke:'#173F39','stroke-width':3,'stroke-linecap':'round'}))mark.setAttribute(name,value);svg.append(square,mark);return svg;};
let lang=new URLSearchParams(location.search).get('lang')==='en'?'en':'zh',system,handles=[],unbind,values={focus:false,choice:'idea',brightness:60,duration:25,query:'',notice:true,cardLevel:58};
const copy=key=>catalogCopy[lang][key],status=text=>{qs('#catalog-status').textContent=text;};
const catalogOptics=mountOpticalDemo(qs('#optical-demo'),{language:lang});
function sample(key,wide=false){const section=document.createElement('section');section.className='catalog-sample'+(wide?' catalog-sample-wide':'');const heading=document.createElement('h3'),name=key==='buttons'?'button':key,entry=componentCatalog.find(item=>item.name===name),code=document.createElement('code');heading.className='component-label';heading.textContent=entry?.[lang]||copy(key);code.textContent=name;heading.append(code);section.append(heading);samples.append(section);return section;}
function make(name,props,parent){const handle=createComponent(name,props);handles.push(handle);parent.append(handle.element);return handle;}
function renderCatalog(){
  catalogOptics.setLanguage(lang);
  const finish=qs('#catalog-material').value,scene=qs('#catalog-scene').value;unbind?.();system?.destroy();handles.forEach(h=>h.destroy());handles=[];samples.replaceChildren();
  document.documentElement.lang=lang==='zh'?'zh-CN':'en';document.querySelectorAll('[data-copy]').forEach(el=>el.textContent=copy(el.dataset.copy));document.querySelectorAll('[data-lang]').forEach(el=>el.setAttribute('aria-pressed',String(el.dataset.lang===lang)));
  const buttons=sample('buttons'),row=document.createElement('div');row.className='catalog-button-row';buttons.append(row);
  make('button',{label:copy('save'),sound:'success',variant:'success',onPress:()=>status(copy('saved'))},row);make('button',{label:copy('disabled'),disabled:true},row);
  make('switch',{label:copy('switch'),checked:values.focus,onChange:value=>{values.focus=value;status(copy(value?'on':'off'));}},sample('switch'));
  make('choices',{label:copy('choices'),value:values.choice,options:['idea','work','life'].map(value=>({value,label:copy(value)})),onChange:value=>{values.choice=value;status(copy(value));}},sample('choices'));
  make('slider',{label:copy('brightness'),value:values.brightness,onChange:value=>{values.brightness=value;system?.renderer?.set({brightness:.65+value*.0035});}},sample('slider'));
  make('stepper',{label:copy('duration'),value:values.duration,unit:copy('unit'),decreaseLabel:copy('less'),increaseLabel:copy('more'),onChange:value=>{values.duration=value;status(`${value} ${copy('unit')}`);}},sample('stepper'));
  const search=make('search',{label:copy('find'),placeholder:copy('placeholder'),onChange:value=>{values.query=value;status(value||copy('ready'));}},sample('search'));search.setValue(values.query);
  const noticeSection=sample('notification'),notice=make('notification',{title:copy('noticeTitle'),description:copy('noticeBody'),dismissLabel:copy('dismiss'),onDismiss:()=>{values.notice=false;restore.element.hidden=false;restore.element.focus();}},noticeSection),restore=make('button',{label:copy('restore'),sound:'restore',onPress:()=>{values.notice=true;notice.show();restore.element.hidden=true;notice.element.querySelector('button').focus();}},noticeSection);notice.element.hidden=!values.notice;restore.element.hidden=values.notice;
  const content=document.createElement('div');content.className='catalog-panel-content';const text=document.createElement('span');text.textContent=copy('panelText');content.append(text);make('panel',{label:copy('panel'),children:[content]},sample('panel'));
  const area=document.createElement('div');area.className='catalog-lens-area';sample('lens',true).append(area);make('lens',{label:copy('lensAria'),caption:copy('lensCaption')},area);
  const cardSample=sample('card-list',true),cardProgress=createComponent('progress',{label:lang==='zh'?'阅读进度':'Reading progress',value:values.cardLevel,completionColor:'gold'}),cardSlider=createComponent('slider',{label:lang==='zh'?'调整进度':'Adjust progress',value:values.cardLevel,onChange:value=>{values.cardLevel=value;cardProgress.setValue(value);}});cardSample.style.setProperty('--lg-card-width','416px');make('card-list',{label:lang==='zh'?'快捷卡片':'Quick cards',previousLabel:lang==='zh'?'上一张卡片':'Previous card',nextLabel:lang==='zh'?'下一张卡片':'Next card',emptyLabel:lang==='zh'?'暂无卡片':'No cards',items:[{id:'capture',label:lang==='zh'?'随手记':'Quick Note',description:lang==='zh'?'图标、名称与说明可以独立成卡。':'An icon, name, and description can stand alone.',icon:catalogCardIcon()},{id:'reading',label:lang==='zh'?'阅读计划':'Reading Plan',description:lang==='zh'?'同一张卡里自由组合现有组件。':'Combine existing controls in the same card.',children:[cardSlider,cardProgress]}]},cardSample);
  make('icon-button',{label:lang==='zh'?'收藏':'Favorite',icon:'heart',pressed:false,onChange:value=>status(String(value))},sample('icon-button'));
  make('toggle-tile',{label:'Wi-Fi',icon:'wifi',checked:true,onLabel:lang==='zh'?'已连接':'Connected',offLabel:lang==='zh'?'已关闭':'Off'},sample('toggle-tile'));
  const options=['idea','work','life'].map(value=>({value,label:copy(value),content:copy(value),icon:value==='idea'?'sun':value==='work'?'focus':'leaf'}));
  make('tabs',{label:lang==='zh'?'内容标签':'Content tabs',options},sample('tabs'));
  make('dock',{label:lang==='zh'?'导航':'Navigation',options,onChange:value=>status(copy(value))},sample('dock'));
  const menuSample=sample('menu',true);menuSample.style.minHeight='300px';make('menu',{label:lang==='zh'?'更多操作':'More actions',options:[{value:'save',label:copy('save'),icon:'heart'},{value:'disabled',label:copy('disabled'),disabled:true}],onAction:()=>status(copy('saved'))},menuSample);
  system=createGlassSystem(stage,{material:finish,scene,audio:{onChange:()=>{qs('#catalog-sound').checked=system.sound.enabled;qs('#catalog-volume').value=Math.round(system.sound.volume*100);qs('#catalog-volume-value').value=`${Math.round(system.sound.volume*100)}%`;if(system.sound.status==='unavailable')status(copy('soundFallback'));}}});
  // The toolbar shares the stage's audio service; it has no second audio context.
  unbind=bindControlSounds(qs('.catalog-toolbar'),system.sound);qs('#catalog-sound').checked=system.sound.enabled;qs('#catalog-volume').value=Math.round(system.sound.volume*100);qs('#catalog-volume-value').value=`${Math.round(system.sound.volume*100)}%`;status(copy('ready'));
}
qs('#catalog-material').addEventListener('change',event=>{system.setMaterial(event.target.value);system.sound.play('select');});
qs('#catalog-scene').addEventListener('change',event=>{system.setScene(event.target.value);system.sound.play('select');});
qs('#catalog-sound').addEventListener('change',event=>{system.sound.set({enabled:event.target.checked});if(event.target.checked)system.sound.play('switchOn');});
qs('#catalog-volume').addEventListener('input',event=>{system.sound.set({volume:Number(event.target.value)/100});system.sound.play('tick');});
document.querySelectorAll('[data-lang]').forEach(button=>button.addEventListener('click',()=>{lang=button.dataset.lang;renderCatalog();}));
renderCatalog();window.addEventListener('pagehide',event=>{if(!event.persisted){catalogOptics.destroy();unbind?.();unbindFocus();system.destroy();handles.forEach(h=>h.destroy());}});
