import {createComponent} from './components.js';
import {createGlassSystem} from './runtime.js';
import {GlassSound,bindControlSounds} from './sound.js';
import {bindKeyboardFocus} from './focus.js';
import {mountOpticalDemo} from './optical-demo.js';
import {mountShowcaseCharts} from './showcase-charts.js';
import {addOpticalRim} from './optical-components.js';
import {opticalSelection,clearOpticalState} from './internal/optics.js';
import {tokens} from './tokens.js';
import {componentCatalog,showcasePatterns,labelComponentSample} from './component-catalog.js';

const scElement=(tag,className,text)=>{const element=document.createElement(tag);element.className=className;if(text!==undefined)element.textContent=text;return element;};
const scAppIcon=kind=>{const svg=document.createElementNS('http://www.w3.org/2000/svg','svg');svg.setAttribute('viewBox','0 0 48 48');svg.setAttribute('aria-hidden','true');svg.setAttribute('focusable','false');svg.classList.add('sc-app-icon');const shape=(tag,attributes)=>{const item=document.createElementNS(svg.namespaceURI,tag);for(const [name,value] of Object.entries(attributes))item.setAttribute(name,value);svg.append(item);};const artwork={notes:[['rect',{x:4,y:4,width:40,height:40,rx:11,fill:'#F5B942'}],['path',{d:'M15 16h18M15 24h14M15 32h10',stroke:'#5B3A12','stroke-width':3,'stroke-linecap':'round'}]],pulse:[['rect',{x:4,y:4,width:40,height:40,rx:11,fill:'#64C7B5'}],['path',{d:'M11 25h7l4-9 6 18 4-9h5',fill:'none',stroke:'#123F3B','stroke-width':3,'stroke-linecap':'round','stroke-linejoin':'round'}]],levels:[['rect',{x:4,y:4,width:40,height:40,rx:11,fill:'#7D91E8'}],['rect',{x:13,y:26,width:5,height:9,rx:2,fill:'#172556'}],['rect',{x:22,y:19,width:5,height:16,rx:2,fill:'#172556'}],['rect',{x:31,y:12,width:5,height:23,rx:2,fill:'#172556'}]],finish:[['rect',{x:4,y:4,width:40,height:40,rx:11,fill:'#F1C765'}],['path',{d:'m14 25 7 7 14-16',fill:'none',stroke:'#553B0C','stroke-width':4,'stroke-linecap':'round','stroke-linejoin':'round'}]]};for(const [tag,attributes] of artwork[kind]||artwork.notes)shape(tag,attributes);return svg;};
const scCopy={
  zh:{navMaterial:'材质',navControls:'组件',navOptics:'光学交互',navCharts:'图与表',language:'English',skip:'跳到内容',title:'可触摸的光。',intro:'看见折射的层次，感受拖动的弹性。让每一次操作，都留下轻轻的回应。',explore:'体验全部组件',heroLabel:'透镜材质体验',lens:'拖动玻璃透镜，或使用方向键移动',lensCaption:'按住，轻轻移动',scene:'背景',grid:'纸面网格',aurora:'流光',ocean:'深海',material:'材质',thick:'厚润',clear:'通透',soft:'柔和',surfaceNote:'拖动透镜，听见玻璃掠过纸面的细微颗粒声。',sound:'交互声音',volume:'音量',audition:'试听摩擦声',soundUnavailable:'声音暂不可用，视觉和操作不受影响。',soundHint:'声音只在操作时响起。速度决定摩擦的轻重。',controlsTitle:'小动作，也有回应。',controlsIntro:'从一次点击，到一段专注。每个控件都有清楚的状态，也有恰到好处的触感。',save:'保存此刻',saved:'已保存',saveStatus:'此刻已保存在当前演示中。',disabled:'暂不可用',focus:'专注模式',focusOn:'已开启专注',focusOff:'已关闭专注',brightness:'明亮程度',duration:'专注时长',unit:'分钟',less:'减少时长',more:'增加时长',panel:'按住拖动面板',panelTitle:'给想法，一点空间。',panelText:'拖动后松手，感受柔和回弹。',noticeTitle:'准备好，进入心流。',noticeText:'从 25 分钟开始，把注意力留给眼前。',dismiss:'收起通知',restore:'恢复通知',controlsHint:'点击、拖动，也可以使用键盘。',footerTitle:'从一束光，开始构建。',footerText:'18 类语义化组件、共享材质与弹性、可独立使用的声音。原生网页，无运行时依赖。',catalog:'打开组件目录',api:'阅读组件 API',lab:'材质实验室',footerNote:'基于 1.0.0 恢复基线继续开发。所有示例只影响当前网页。',friction:'玻璃 × 纸面',codeLabel:'最小接入示例',brand:'Lens'},
  en:{navMaterial:'Material',navControls:'Controls',navOptics:'Interactions',navCharts:'Charts & tables',language:'中文',skip:'Skip to content',title:'Light, within reach.',intro:'See the layers of refraction. Feel the spring of a gesture. Let every action leave a quiet response.',explore:'Explore the components',heroLabel:'Lens material playground',lens:'Drag the glass lens, or move it with the arrow keys',lensCaption:'Hold. Move gently.',scene:'Scene',grid:'Paper grid',aurora:'Aurora',ocean:'Ocean',material:'Material',thick:'Thick',clear:'Clear',soft:'Soft',surfaceNote:'Move the lens to hear the fine grain of glass brushing over paper.',sound:'Interaction sound',volume:'Volume',audition:'Preview friction',soundUnavailable:'Audio is unavailable. Visual feedback and controls still work.',soundHint:'Sound follows your gesture. Speed shapes its texture.',controlsTitle:'Small gestures. Clear responses.',controlsIntro:'From a single click to a moment of focus. Every control has a clear state and a considered feel.',save:'Save this moment',saved:'Saved',saveStatus:'This moment is saved in the current demo.',disabled:'Unavailable',focus:'Focus mode',focusOn:'Focus enabled',focusOff:'Focus disabled',brightness:'Brightness',duration:'Focus duration',unit:'min',less:'Decrease duration',more:'Increase duration',panel:'Hold to drag the panel',panelTitle:'Make room for an idea.',panelText:'Drag, release, and feel the soft return.',noticeTitle:'Ready for a little flow.',noticeText:'Start with 25 minutes. Keep your attention here.',dismiss:'Dismiss notification',restore:'Restore notification',controlsHint:'Click, drag, or use the keyboard.',footerTitle:'Build from a little light.',footerText:'18 semantic controls. Shared glass and springs. An independent sound engine. Native web, with no runtime dependencies.',catalog:'Open component catalog',api:'Read the component API',lab:'Material lab',footerNote:'Built on the restored 1.0.0 baseline. Every demo stays within this page.',friction:'Glass × paper',codeLabel:'A minimal integration',brand:'Lens'},
};

export function mountShowcase(root,{language='zh'}={}){
  let lang=language==='en'?'en':'zh',systems=[],handles=[],abort,optics,charts,auditionFrame=0;
  const state={material:'thick',scene:'grid',focus:false,brightness:70,duration:25,saved:false,notice:true,optics:null,charts:null,favorite:false,wifi:true,bluetooth:false,tab:'overview',dock:'home',action:'ready',cardConnected:false,cardLevel:62,cardComplete:true};
  const lifecycle=new AbortController(),sound=new GlassSound({onChange:()=>syncSound()}),unbindSounds=bindControlSounds(root,sound),unbindFocus=bindKeyboardFocus(document);
  const stopAudition=()=>{cancelAnimationFrame(auditionFrame);auditionFrame=0;sound.endFriction();};
  const dispose=()=>{stopAudition();abort?.abort();if(optics)state.optics=optics.snapshot();if(charts)state.charts=charts.snapshot();optics?.destroy();charts?.destroy();systems.forEach(system=>system.destroy());handles.forEach(handle=>handle.destroy());systems=[];handles=[];};
  function syncSound(){
    const control=root.querySelector('#showcase-sound'),volume=root.querySelector('#showcase-volume'),output=root.querySelector('#showcase-volume-output'),preview=root.querySelector('#showcase-audition'),notice=root.querySelector('#showcase-sound-status');
    if(!control)return;control.checked=sound.enabled;volume.value=Math.round(sound.volume*100);output.value=`${Math.round(sound.volume*100)}%`;volume.disabled=!sound.enabled;preview.disabled=!sound.enabled||sound.volume===0;notice.textContent=scCopy[lang][sound.status==='unavailable'?'soundUnavailable':'soundHint'];
    if(!sound.enabled||!sound.volume)stopAudition();
  }
  function render(){
    dispose();root.replaceChildren();abort=new AbortController();const signal=abort.signal,c=scCopy[lang];root.classList.add('showcase');document.documentElement.lang=lang==='zh'?'zh-CN':'en';document.title=lang==='zh'?'Lens · 完整展示':'Lens · Showcase';
    const link=(label,href,className='')=>{const a=scElement('a',className,label);a.href=href;return a;};
    const button=(label,className,handler)=>{const item=scElement('button',className,label);item.type='button';item.addEventListener('click',handler,{signal});return item;};
    const make=(name,props,parent)=>{const handle=createComponent(name,props);parent.append(handle.element);handles.push(handle);return handle;};
    const glass=stage=>{const system=createGlassSystem(stage,{scene:'aurora',motion:false,audio:{enabled:false,storage:null}});systems.push(system);return system;};
    root.append(link(c.skip,'#material','sc-skip'));
    const header=scElement('header','sc-header'),brand=link(c.brand,'#material','sc-brand'),nav=scElement('nav','sc-nav');nav.setAttribute('aria-label',lang==='zh'?'页面导航':'Page navigation');
    for(const [label,href] of [[c.navMaterial,'#material'],[c.navControls,'#component-index'],[c.navOptics,'#optical-demo'],[c.navCharts,'#charts']])nav.append(link(label,href));
    const languageButton=button(c.language,'sc-language',()=>{lang=lang==='zh'?'en':'zh';render();root.querySelector('.sc-language').focus({preventScroll:true});});header.append(brand,nav,languageButton);root.append(header);
    const main=scElement('main','sc-main'),hero=scElement('section','sc-hero');hero.id='material';const introduction=scElement('div','sc-hero-copy');introduction.append(scElement('h1','',c.title),scElement('p','',c.intro),link(c.explore,'#component-index','sc-primary-link'));hero.append(introduction);
    const materialWrapper=scElement('div','sc-material-specimen'),materialStage=scElement('div','sc-material-stage');materialStage.setAttribute('aria-label',c.heroLabel);make('lens',{label:c.lens,caption:c.lensCaption},materialStage);materialWrapper.append(materialStage);labelComponentSample(materialWrapper,'lens',lang);hero.append(materialWrapper);main.append(hero);
    const heroSystem=glass(materialStage);heroSystem.setScene(state.scene);heroSystem.setMaterial(state.material);
    const materialTools=scElement('div','sc-material-tools'),presetLabel=scElement('span','sc-control-label',c.material),presets=scElement('div','sc-segment');presets.setAttribute('role','group');presets.setAttribute('aria-label',c.material);const presetButtons=[];
    for(const key of ['thick','clear','soft']){const item=button(c[key],'',()=>{state.material=key;heroSystem.setMaterial(key);presetButtons.forEach(entry=>entry.item.setAttribute('aria-pressed',String(entry.key===key)));sound.play('select');});item.setAttribute('aria-pressed',String(state.material===key));presets.append(item);presetButtons.push({key,item});}
    const sceneLabel=scElement('label','sc-select'),scene=scElement('select','');scene.setAttribute('aria-label',c.scene);for(const key of ['grid','aurora','ocean']){const option=scElement('option','',c[key]);option.value=key;scene.append(option);}scene.value=state.scene;scene.addEventListener('change',()=>{state.scene=scene.value;heroSystem.setScene(scene.value);},{signal});sceneLabel.append(scElement('span','',c.scene),scene);materialTools.append(presetLabel,presets,sceneLabel);main.append(materialTools);
    const soundStrip=scElement('section','sc-sound-strip'),soundIntro=scElement('div','sc-sound-intro');soundIntro.append(scElement('h2','',c.friction),scElement('p','',c.surfaceNote));
    const soundControls=scElement('div','sc-sound-controls'),toggleLabel=scElement('label','sc-sound-toggle'),toggle=scElement('input','');toggle.type='checkbox';toggle.id='showcase-sound';toggle.addEventListener('change',()=>sound.set({enabled:toggle.checked}),{signal});toggleLabel.append(toggle,scElement('span','',c.sound));
    const volumeLabel=scElement('label','sc-volume'),volume=scElement('input',''),volumeOutput=scElement('output','');volume.id='showcase-volume';volume.type='range';volume.min=0;volume.max=100;volume.step=1;volumeOutput.id='showcase-volume-output';volume.setAttribute('aria-label',c.volume);volume.addEventListener('input',()=>sound.set({volume:Number(volume.value)/100}),{signal});volumeLabel.append(scElement('span','',c.volume),volume,volumeOutput);
    const preview=button(c.audition,'sc-quiet-button',async()=>{stopAudition();if(!await sound.startFriction())return;const start=performance.now();const sweep=now=>{const t=(now-start)/1400;if(t>=1){stopAudition();return;}sound.updateFriction(120+Math.sin(t*Math.PI)*650);auditionFrame=requestAnimationFrame(sweep);};auditionFrame=requestAnimationFrame(sweep);});preview.id='showcase-audition';
    const soundStatus=scElement('p','sc-sound-status');soundStatus.id='showcase-sound-status';soundStatus.setAttribute('role','status');soundControls.append(toggleLabel,volumeLabel,preview,soundStatus);soundStrip.append(soundIntro,soundControls);main.append(soundStrip);
    const index=scElement('section','sc-component-index'),indexList=scElement('ul','sc-component-links');index.id='component-index';index.append(scElement('h2','',lang==='zh'?'组件索引':'Component index'),scElement('p','sc-intro',lang==='zh'?'18 个可复用组件与 4 个数据展示。按固定名称定位，每处都附有使用示例。':'18 reusable components and 4 data compositions. Find each by its stable name and inspect its usage example.'));
    for(const entry of [...componentCatalog,...showcasePatterns]){const item=scElement('li',''),anchor=link('',`#component-${entry.name}`);anchor.append(scElement('span','',entry[lang]),scElement('code','',entry.name));item.append(anchor);indexList.append(item);}index.append(indexList);main.append(index);
    const controls=scElement('section','sc-controls-section');controls.id='controls';const controlsCopy=scElement('div','sc-controls-copy');controlsCopy.append(scElement('h2','',c.controlsTitle),scElement('p','sc-intro',c.controlsIntro));const controlStatus=scElement('output','sc-control-status',c.controlsHint);controlStatus.setAttribute('aria-live','polite');controlsCopy.append(controlStatus);
    const draggableContent=scElement('div','sc-panel-content');draggableContent.append(scElement('strong','',c.panelTitle),scElement('p','',c.panelText));const panelSample=scElement('section','sc-panel-specimen'),panelStage=scElement('div','sc-panel-stage');make('panel',{label:c.panel,children:[draggableContent]},panelStage);panelSample.append(panelStage);labelComponentSample(panelSample,'panel',lang);controlsCopy.append(panelSample);glass(panelStage);
    const board=scElement('div','sc-control-board'),actionRow=scElement('div','sc-button-row');board.append(actionRow);const save=make('button',{label:state.saved?c.saved:c.save,variant:'success',sound:'success',onPress:()=>{state.saved=true;save.element.textContent=c.saved;controlStatus.value=c.saveStatus;}},actionRow);make('button',{label:c.disabled,disabled:true},actionRow);
    const focusRow=scElement('div','sc-control-row');focusRow.append(scElement('span','',c.focus));make('switch',{label:c.focus,checked:state.focus,onChange:value=>{state.focus=value;controlStatus.value=value?c.focusOn:c.focusOff;}},focusRow);board.append(focusRow);
    let boardSystem;const sliderSample=scElement('section','sc-control-sample');board.append(sliderSample);make('slider',{label:c.brightness,value:state.brightness,onChange:value=>{state.brightness=value;boardSystem?.renderer?.set({brightness:.65+value*.004});}},sliderSample);
    const stepRow=scElement('div','sc-control-row');stepRow.append(scElement('span','',c.duration));make('stepper',{label:c.duration,value:state.duration,unit:c.unit,decreaseLabel:c.less,increaseLabel:c.more,onChange:value=>{state.duration=value;}},stepRow);board.append(stepRow);
    const noticeSample=scElement('section','sc-control-sample');board.append(noticeSample);const notice=make('notification',{title:c.noticeTitle,description:c.noticeText,dismissLabel:c.dismiss,onDismiss:()=>{state.notice=false;restore.element.hidden=false;restore.element.focus();}},noticeSample),restore=make('button',{label:c.restore,sound:'restore',onPress:()=>{state.notice=true;notice.show();restore.element.hidden=true;notice.element.querySelector('button').focus();}},noticeSample);notice.element.hidden=!state.notice;restore.element.hidden=state.notice;
    for(const [sample,name] of [[actionRow,'button'],[focusRow,'switch'],[sliderSample,'slider'],[stepRow,'stepper'],[noticeSample,'notification']])labelComponentSample(sample,name,lang);
    controls.append(controlsCopy,board);main.append(controls);boardSystem=glass(board);boardSystem.renderer?.set({brightness:.65+state.brightness*.004});
    const patterns=scElement('section','sc-patterns'),patternBoard=scElement('div','sc-pattern-board');patterns.append(scElement('h2','',lang==='zh'?'导航与操作':'Navigation and actions'),scElement('p','sc-intro',lang==='zh'?'从原版实验室补齐的控件。点击、拖动，或使用键盘检查它们的状态。':'Controls from the original material lab. Click, drag, or use the keyboard to inspect their states.'),patternBoard);main.append(patterns);
    const sample=name=>{const section=scElement('section',`sc-pattern-sample sc-pattern-${name}`);patternBoard.append(section);return section;};
    const iconSample=sample('icon-button'),iconRow=scElement('div','sc-pattern-row');iconSample.append(iconRow);const favorite=make('icon-button',{label:lang==='zh'?'收藏组件':'Favorite components',icon:'heart',pressed:state.favorite,onChange:value=>{state.favorite=value;}},iconRow);make('icon-button',{label:lang==='zh'?'重置收藏':'Reset favorite',icon:'reset',onPress:()=>{state.favorite=false;favorite.setValue(false);}},iconRow);make('icon-button',{label:lang==='zh'?'禁用图标按钮':'Disabled icon button',icon:'plus',disabled:true},iconRow);labelComponentSample(iconSample,'icon-button',lang);
    const tileSample=sample('toggle-tile'),tileRow=scElement('div','sc-pattern-row');tileSample.append(tileRow);for(const key of ['wifi','bluetooth'])make('toggle-tile',{label:key==='wifi'?'Wi-Fi':lang==='zh'?'蓝牙':'Bluetooth',icon:key,checked:state[key],onLabel:lang==='zh'?'已连接':'Connected',offLabel:lang==='zh'?'已关闭':'Off',onChange:value=>{state[key]=value;}},tileRow);labelComponentSample(tileSample,'toggle-tile',lang);
    const tabsSample=sample('tabs');make('tabs',{label:lang==='zh'?'组件视图':'Component view',value:state.tab,options:[{value:'overview',label:lang==='zh'?'总览':'Overview',content:lang==='zh'?'标签页让相关内容共享一处空间。拖动玻璃选中层，或用方向键切换。':'Tabs give related content one shared space. Drag the glass selection or use the arrow keys.'},{value:'material',label:lang==='zh'?'材质':'Material',content:lang==='zh'?'厚润、通透与柔和材质共用同一组光学参数。':'Thick, clear and soft finishes share the same optical parameters.'},{value:'disabled',label:lang==='zh'?'禁用':'Disabled',disabled:true}],onChange:value=>{state.tab=value;}},tabsSample);labelComponentSample(tabsSample,'tabs',lang);
    const dockSample=sample('dock'),dockStatus=scElement('output','sc-pattern-status');dockStatus.setAttribute('aria-live','polite');const dockNames={home:lang==='zh'?'总览':'Overview',material:lang==='zh'?'材质':'Material',saved:lang==='zh'?'收藏':'Saved'};const showDock=value=>{dockStatus.value=lang==='zh'?`当前视图 · ${dockNames[value]}`:`Current view · ${dockNames[value]}`;};make('dock',{label:lang==='zh'?'浮动导航示例':'Floating navigation example',value:state.dock,options:[{value:'home',label:dockNames.home,icon:'home'},{value:'material',label:dockNames.material,icon:'layers'},{value:'saved',label:dockNames.saved,icon:'heart'}],onChange:value=>{state.dock=value;showDock(value);}},dockSample);showDock(state.dock);dockSample.append(dockStatus);labelComponentSample(dockSample,'dock',lang);
    const menuSample=sample('menu'),menuStatus=scElement('output','sc-pattern-status'),menuMessages=lang==='zh'?{ready:'打开菜单，试试方向键和 Escape。',save:'已在演示中保存。',reset:'已选择重置操作。'}:{ready:'Open the menu. Try arrow keys and Escape.',save:'Saved in this demo.',reset:'Reset action selected.'};menuStatus.setAttribute('aria-live','polite');menuStatus.value=menuMessages[state.action];make('menu',{label:lang==='zh'?'更多操作':'More actions',options:[{value:'save',label:lang==='zh'?'保存示例':'Save example',icon:'heart'},{value:'reset',label:lang==='zh'?'重置示例':'Reset example',icon:'reset'},{value:'disabled',label:lang==='zh'?'暂不可用':'Unavailable',disabled:true}],onAction:value=>{state.action=value;menuStatus.value=menuMessages[value];}},menuSample);menuSample.append(menuStatus);labelComponentSample(menuSample,'menu',lang);glass(patternBoard);
    const cardSection=scElement('section','sc-card-list-section'),cardSample=scElement('div','sc-card-list-sample'),connectionStatus=scElement('output','sc-card-status'),completionStatus=scElement('output','sc-card-status');cardSection.append(scElement('h2','',lang==='zh'?'一列透镜，多种内容。':'One lens row. Many kinds of content.'),scElement('p','sc-intro',lang==='zh'?'横向卡片自动循环；拖动卡片空白处即可浏览，悬停或操作控件时会暂停。按钮、滑杆与进度可以自由组合。':'The horizontal cards loop automatically. Drag from blank card space to browse; hovering or using a control pauses the motion. Buttons, sliders, and progress can be freely combined.'),cardSample);main.append(cardSection);
    connectionStatus.setAttribute('aria-live','polite');connectionStatus.value=state.cardConnected?(lang==='zh'?'同步已开启':'Sync enabled'):(lang==='zh'?'尚未连接':'Not connected');let connectButton;connectButton=createComponent('button',{label:state.cardConnected?(lang==='zh'?'断开':'Disconnect'):(lang==='zh'?'连接':'Connect'),onPress:()=>{state.cardConnected=!state.cardConnected;connectionStatus.value=state.cardConnected?(lang==='zh'?'同步已开启':'Sync enabled'):(lang==='zh'?'尚未连接':'Not connected');connectButton.element.firstChild.nodeValue=state.cardConnected?(lang==='zh'?'断开':'Disconnect'):(lang==='zh'?'连接':'Connect');opticalSelection(connectButton.element,state.cardConnected,'green',true);}});addOpticalRim(connectButton.element);opticalSelection(connectButton.element,state.cardConnected,'green',false);const destroyConnectButton=connectButton.destroy;connectButton.destroy=()=>{clearOpticalState(connectButton.element);connectButton.element.querySelector('.lg-optic-beam')?.getAnimations().forEach(animation=>animation.cancel());destroyConnectButton();};
    const levelProgress=createComponent('progress',{label:lang==='zh'?'专注强度':'Focus level',value:state.cardLevel,completionColor:'gold',wave:true}),levelSlider=createComponent('slider',{label:lang==='zh'?'调整强度':'Adjust intensity',value:state.cardLevel,onChange:value=>{state.cardLevel=value;levelProgress.setValue(value);}});
    completionStatus.setAttribute('aria-live','polite');completionStatus.value=state.cardComplete?(lang==='zh'?'本轮已完成':'Session complete'):(lang==='zh'?'还差最后一步':'One step remains');const goldProgress=createComponent('progress',{label:lang==='zh'?'今日目标':'Today’s goal',value:state.cardComplete?100:72,completionColor:'gold',completeLabel:lang==='zh'?'已完成':'Complete',wave:true});let completionButton;completionButton=createComponent('button',{label:state.cardComplete?(lang==='zh'?'再来一轮':'Start again'):(lang==='zh'?'完成目标':'Complete goal'),variant:'success',sound:state.cardComplete?'reset':'success',onPress:()=>{state.cardComplete=!state.cardComplete;goldProgress.setValue(state.cardComplete?100:72);completionStatus.value=state.cardComplete?(lang==='zh'?'本轮已完成':'Session complete'):(lang==='zh'?'还差最后一步':'One step remains');completionButton.element.textContent=state.cardComplete?(lang==='zh'?'再来一轮':'Start again'):(lang==='zh'?'完成目标':'Complete goal');queueMicrotask(()=>{completionButton.element.dataset.lgSound=state.cardComplete?'reset':'success';});}});
    make('card-list',{label:lang==='zh'?'推荐应用':'Featured apps',previousLabel:lang==='zh'?'上一张':'Previous',nextLabel:lang==='zh'?'下一张':'Next',pauseLabel:lang==='zh'?'暂停自动滚动':'Pause automatic scrolling',playLabel:lang==='zh'?'继续自动滚动':'Resume automatic scrolling',autoScroll:true,emptyLabel:lang==='zh'?'暂无卡片':'No cards',items:[{id:'notes',label:lang==='zh'?'便笺':'Notes',description:lang==='zh'?'快速记下刚刚闪过的想法。':'Catch a thought before it slips away.',icon:scAppIcon('notes')},{id:'pulse',label:lang==='zh'?'脉动同步':'Pulse Sync',description:lang==='zh'?'让当下进度保持连接。':'Keep the current moment in sync.',icon:scAppIcon('pulse'),children:[connectButton,connectionStatus]},{id:'levels',label:lang==='zh'?'专注调音台':'Focus Mixer',description:lang==='zh'?'滑动并立即看见强度变化。':'Slide and see the intensity respond.',icon:scAppIcon('levels'),children:[levelSlider,levelProgress]},{id:'finish',label:lang==='zh'?'金色收尾':'Golden Finish',description:lang==='zh'?'完成时让光带落在金色。':'Let the light settle into gold at completion.',icon:scAppIcon('finish'),children:[goldProgress,completionButton,completionStatus]}]},cardSample);labelComponentSample(cardSample,'card-list',lang);glass(cardSample);
    const opticalHost=scElement('section','');opticalHost.id='optical-demo';main.append(opticalHost);optics=mountOpticalDemo(opticalHost,{language:lang,initialState:state.optics||{}});
    const chartHost=scElement('section','sc-charts-section');chartHost.id='charts';main.append(chartHost);charts=mountShowcaseCharts(chartHost,{language:lang,initialState:state.charts||{}});
    const referenceRoot=document.documentElement.dataset.standalone==='true'?'lab/design-system/':'../';
    const footer=scElement('footer','sc-footer'),footerCopy=scElement('div','');footerCopy.append(scElement('h2','',c.footerTitle),scElement('p','',c.footerText));const footerLinks=scElement('div','sc-footer-links');footerLinks.append(link(c.catalog,`${referenceRoot}index.html`),link(c.api,`${referenceRoot}README.md`),link(c.lab,document.documentElement.dataset.standalone==='true'?'lens.html':'../../index.html'));footerCopy.append(footerLinks);
    const code=scElement('pre','sc-code'),codeText=scElement('code','','const lens = createComponent(\'lens\', {\n  label: \'Move the glass\'\n});\nstage.append(lens.element);\nconst glass = createGlassSystem(stage);');code.setAttribute('aria-label',c.codeLabel);code.append(codeText);footer.append(footerCopy,code,scElement('p','sc-footer-note',`${c.footerNote}  ${tokens.version}`));main.append(footer);root.append(main);syncSound();
  }
  document.addEventListener('visibilitychange',()=>{if(document.hidden)stopAudition();},{signal:lifecycle.signal});
  render();return {destroy(){dispose();lifecycle.abort();unbindSounds();unbindFocus();sound.destroy();root.replaceChildren();}};
}
