import {test} from 'node:test';
import assert from 'node:assert/strict';
await import('../src/core.js');
await import('../src/dynamics.js');
await import('../src/sound.js');
const m=globalThis.Overture.model;

test('exposure controls clamp values at both boundaries',()=>{assert.equal(m.range(-20,0,100),0);assert.equal(m.range(150,0,100),100);});
test('fractional steps remain stable and avoid floating point text artifacts',()=>{assert.equal(m.range(.30000000004,0,1,.1),.3);assert.equal(m.range(.79,.1,.9,.2),.7);});
test('invalid range definitions are rejected instead of silently misbehaving',()=>{assert.throws(()=>m.range(0,10,1),RangeError);assert.throws(()=>m.range(1,0,10,0),RangeError);});
test('pagination handles empty data and clamps a stale current page',()=>{assert.deepEqual(m.page(9,0,6),{page:1,pages:1,start:0,end:0});assert.deepEqual(m.page(9,13,6),{page:3,pages:3,start:12,end:13});});
test('pagination normalizes invalid page sizes',()=>{assert.deepEqual(m.page(2,4,0),{page:2,pages:4,start:1,end:2});});
test('keyword entry trims, removes duplicates, and ignores empty input',()=>{assert.deepEqual(m.tags('光, 舞台,光,,'),['光','舞台']);assert.deepEqual(m.tags(null),[]);});
test('keyword entry caps its public data model at twelve values',()=>{assert.equal(m.tags(Array.from({length:20},(_,i)=>String(i))).length,12);});
test('numeric archive sorting is stable and does not mutate input',()=>{const rows=[{n:2,id:'a'},{n:1,id:'b'},{n:2,id:'c'}];assert.deepEqual(m.sort(rows,'n').map(x=>x.id),['b','a','c']);assert.deepEqual(rows.map(x=>x.id),['a','b','c']);assert.deepEqual(m.sort(rows,'n',-1).map(x=>x.id),['a','c','b']);});
test('file intake rejects unsupported data and excessive file sizes',()=>{assert.match(m.file({type:'text/html',size:10}),/PNG/);assert.match(m.file({type:'image/png',size:11*1024*1024}),/10 MB/);assert.equal(m.file({type:'image/webp',size:512}), '');});
test('user text is escaped before entering component templates',()=>{assert.equal(globalThis.Overture.escape('<img a="x" onload=\'bad\'>&'), '&lt;img a=&quot;x&quot; onload=&#39;bad&#39;&gt;&amp;');});
test('silk deformation stays finite, shallow and responds to tension',async()=>{const {silkPoint}=await import('../dist/assets/engine.mjs');for(const amount of [0,.5,1])for(let u=0;u<=1;u+=.05)for(let v=0;v<=1;v+=.05){const p=silkPoint(u,v,amount);assert.ok(p.every(Number.isFinite));assert.ok(Math.abs(p[2])<.2);}assert.notDeepEqual(silkPoint(.8,.3,0),silkPoint(.8,.3,1));assert.deepEqual(silkPoint(.5,.5,.5),[0,0,0]);});
test('all catalog names are backed by registered runtime components',async()=>{for(const f of ['controls','overlays','media','contact','light','film','brand'])await import(`../src/${f}.js`);const {components}=await import('../src/catalog-data.mjs');assert.equal(components.length,46);assert.equal(globalThis.Overture.registry.size,46);for(const comp of components)assert.ok(globalThis.Overture.registry.has(comp.name),comp.name);});

await import('../src/light.js');
test('photo-wall camera clamps to its first and last pinned photograph',()=>{const stops=[[10,20],[90,100],[140,40]];assert.deepEqual(m.wallCamera(-1,stops),{x:10,y:20,index:0});assert.deepEqual(m.wallCamera(2,stops),{x:140,y:40,index:2});});
test('photo-wall camera is continuous through every pin and reports the nearest frame',()=>{const stops=[[0,0],[600,400],[1300,150],[2000,500]];for(let i=0;i<stops.length;i++){const p=i/(stops.length-1),center=m.wallCamera(p,stops);assert.equal(center.x,stops[i][0]);assert.equal(center.y,stops[i][1]);assert.equal(center.index,i);const left=m.wallCamera(p-1e-6,stops),right=m.wallCamera(p+1e-6,stops);assert.ok(Math.hypot(right.x-left.x,right.y-left.y)<.001);}});
test('photo-wall camera has safe empty and single-image states',()=>{assert.deepEqual(m.wallCamera(.5,[]),{x:0,y:0,index:0});assert.deepEqual(m.wallCamera(.8,[[32,51]]),{x:32,y:51,index:0});});

test('two mouse-wheel notches advance exactly one photo',()=>{const first=m.wheelStep({},100);assert.equal(first.step,0);assert.equal(first.pending,1);const second=m.wheelStep(first,100);assert.equal(second.step,1);assert.equal(second.pending,0);});
test('changing wheel direction discards the previous half-step',()=>{const first=m.wheelStep({},120),reverse=m.wheelStep(first,-120);assert.equal(reverse.step,0);assert.equal(reverse.pending,1);assert.equal(m.wheelStep(reverse,-120).step,-1);});
test('small trackpad deltas accumulate without skipping photographs',()=>{let state={};for(let i=0;i<9;i++){state=m.wheelStep(state,20);assert.equal(state.step,0);}state=m.wheelStep(state,20);assert.equal(state.step,1);assert.equal(state.pending,0);});
test('large wheel events cannot count as more than one notch',()=>{const first=m.wheelStep({},3000);assert.equal(first.step,0);assert.equal(first.pending,1);assert.equal(m.wheelStep(first,3000).step,1);});
test('line and page wheel units preserve the two-notch rhythm',()=>{for(const [delta,mode] of [[3,1],[1,2]]){const first=m.wheelStep({},delta,mode);assert.equal(first.step,0);assert.equal(m.wheelStep(first,delta,mode).step,1);}});
test('wheel jitter and invalid input do not advance the photo',()=>{const state=m.wheelStep({},100);for(const delta of [0,.1,NaN,Infinity]){const next=m.wheelStep(state,delta);assert.equal(next.step,0);assert.equal(next.pending,1);}});

test('flashlight changes only on the third wheel notch, including reverse input',()=>{let state={};for(const direction of [1,-1]){state=m.wheelStep(state,direction*100,0,3);assert.equal(state.step,0);assert.equal(state.pending,1);state=m.wheelStep(state,direction*100,0,3);assert.equal(state.step,0);assert.equal(state.pending,2);state=m.wheelStep(state,direction*100,0,3);assert.equal(state.step,direction);assert.equal(state.pending,0);}});

await import('../src/film.js');
test('film pull clamps to the leader and the tail, and rejects invalid input',()=>{assert.equal(m.rollPull(-50,120,900),120);assert.equal(m.rollPull(5000,120,900),900);assert.equal(m.rollPull(NaN,120,900),120);assert.equal(m.rollPull(400,120,900),400);});
test('spool turn is monotonic in the pulled length and bounded to 0..1',()=>{let last=-1;for(let p=0;p<=1000;p+=25){const t=m.spoolTurn(p,120,900);assert.ok(t>=last&&t>=0&&t<=1);last=t;}assert.equal(m.spoolTurn(900,120,900),1);assert.equal(m.spoolTurn(10,0,0),0);});
test('a frame becomes a print only when pulled clearly downward or dropped on the table',()=>{assert.equal(m.printDrop(0,80),true);assert.equal(m.printDrop(200,80),false);assert.equal(m.printDrop(0,-120),false);assert.equal(m.printDrop(0,20),false);assert.equal(m.printDrop(300,10,true),true);});
test('three themes define every colour token, and Nocturne keeps vermilion for action',async()=>{const fs=await import('node:fs');const t=JSON.parse(fs.readFileSync(new URL('../project/tokens.json',import.meta.url),'utf8'));const ids=t.color.themes.map(x=>x.id);assert.deepEqual(ids,['stage','paper','nocturne']);for(const tok of t.color.tokens)for(const id of ids)assert.match(tok.value[id],/^#[0-9a-f]{6}$/i,`${tok.name} ${id}`);const get=n=>t.color.tokens.find(x=>x.name===n).value;assert.equal(get('ov-accent').nocturne,get('ov-accent').stage);assert.ok(get('ov-cold'));assert.ok(get('ov-indigo'));assert.deepEqual(globalThis.Overture.themes,ids);});
test('cold text colours keep at least 4.5:1 contrast on their theme background',async()=>{const fs=await import('node:fs');const t=JSON.parse(fs.readFileSync(new URL('../project/tokens.json',import.meta.url),'utf8'));const lum=h=>{const c=[1,3,5].map(i=>parseInt(h.slice(i,i+2),16)/255).map(v=>v<=.03928?v/12.92:((v+.055)/1.055)**2.4);return .2126*c[0]+.7152*c[1]+.0722*c[2];};const ratio=(a,b)=>{const x=lum(a),y=lum(b);return (Math.max(x,y)+.05)/(Math.min(x,y)+.05);};const get=n=>t.color.tokens.find(x=>x.name===n).value;for(const id of ['stage','paper','nocturne'])for(const n of ['ov-cold','ov-focus','ov-text','ov-muted'])assert.ok(ratio(get(n)[id],get('ov-bg')[id])>=4.5,`${n} on ${id}`);});

// 1.3 motion kernel
const K=globalThis.Overture.motion;
const tokenFile=async()=>JSON.parse((await import('node:fs')).readFileSync(new URL('../project/tokens.json',import.meta.url),'utf8'));
const spin=ms=>{const end=performance.now()+ms;while(performance.now()<end);};
test('spring solution honours its initial state and comes to rest for every damping regime',()=>{for(const p of [{stiffness:140,damping:3.2},{stiffness:100,damping:20},{stiffness:100,damping:40}]){const [x0,v0]=K.solve(p,-1,2.5,0);assert.ok(Math.abs(x0+1)<1e-9&&Math.abs(v0-2.5)<1e-9);const h=1e-6,[a]=K.solve(p,-1,2.5,.3),[b]=K.solve(p,-1,2.5,.3+h),[,v]=K.solve(p,-1,2.5,.3+h/2);assert.ok(Math.abs((b-a)/h-v)<1e-3,'velocity is the derivative');const [x]=K.solve(p,-1,2.5,12);assert.ok(Math.abs(x)<1e-3);}});
test('presets keep their character: snap overshoots a little, settle and stage do not, resonance rings',()=>{const peak=name=>{let m=0;for(let t=0;t<4;t+=.002)m=Math.max(m,1+K.solve(K.presets[name],-1,0,t)[0]);return m;};assert.ok(peak('snap')>1.02&&peak('snap')<1.05);assert.ok(peak('settle')<1.002&&peak('stage')<1.002);assert.ok(peak('resonance')>1.5);assert.ok(K.time('snap')<K.time('settle')&&K.time('settle')<K.time('stage'));});
test('retargeting a moving spring keeps its position and velocity continuous',()=>{const s=K.spring({preset:'settle',value:0});s.to(100);spin(25);const x=s.value,v=s.velocity;s.to(-40);const x2=s.value,v2=s.velocity;assert.ok(x>0&&v>0);assert.ok(Math.abs(x2-x)<2,`position ${x} → ${x2}`);assert.ok(Math.abs(v2-v)/Math.abs(v)<.1,`velocity ${v} → ${v2}`);s.stop();});
test('a frozen spring holds its displacement and velocity, and thawing resumes the same motion',()=>{const s=K.spring({preset:'resonance',value:0});s.to(1);spin(20);s.freeze(true);const x=s.value,v=s.velocity;spin(30);assert.equal(s.value,x);assert.equal(s.velocity,v);assert.ok(s.frozen&&!s.moving);s.freeze(false);assert.ok(s.moving);assert.ok(Math.abs(s.value-x)<.05);s.stop();});
test('reduced motion lands every spring immediately',async()=>{const O=globalThis.Overture;O.config.motion='reduce';try{const seen=[];const s=K.spring({value:[0,0],onUpdate:v=>seen.push(v)});const done=await s.to([3,4]);assert.equal(done,true);assert.deepEqual(s.value,[3,4]);assert.deepEqual(seen.at(-1),[3,4]);}finally{O.config.motion='system';}});
test('spring tokens mirror the runtime presets and the CSS easings are generated from them',async()=>{const t=await tokenFile();for(const [name,p] of Object.entries(K.presets)){const tok=t.spring.tokens.find(x=>x.name===`ov-spring-${name}`);assert.ok(tok,name);const [,k,c]=tok.value.match(/stiffness ([\d.]+) · damping ([\d.]+)/);assert.equal(+k,p.stiffness);assert.equal(+c,p.damping);}const get=n=>t.motion.tokens.find(x=>x.name===n).value;assert.equal(get('ov-spring'),K.cssEasing('snap'));assert.equal(get('ov-settle'),K.cssEasing('settle'));assert.equal(get('ov-spring-time'),`${K.time('snap')}ms`);assert.equal(get('ov-settle-time'),`${K.time('settle')}ms`);});
test('generated linear() easings start at 0, end at 1 and stay near the target',()=>{for(const name of ['snap','settle']){const pts=K.cssEasing(name).slice(7,-1).split(', ').map(Number);assert.equal(pts[0],0);assert.equal(pts.at(-1),1);assert.ok(pts.every(v=>v>=0&&v<1.05));}});
test('the film strip stretches past its ends with bounded resistance, and the inverse recovers the pointer',()=>{assert.equal(m.rubber(300,100,900),300);let last=900;for(let x=900;x<5000;x+=50){const y=m.rubber(x,100,900);assert.ok(y>=last&&y<900+140);last=y;}assert.ok(m.rubber(40,100,900)<100&&m.rubber(-9999,100,900)>100-140);for(const x of [20,950,1400,-300])assert.ok(Math.abs(m.unrubber(m.rubber(x,100,900),100,900)-x)<1e-6,String(x));assert.equal(m.rubber(NaN,100,900),100);});
test('a thrown contact strip comes to rest on the frame its momentum reaches',()=>{assert.equal(m.filmRest(-380,0,190),2);assert.equal(m.filmRest(-380,-1000,190),3);assert.equal(m.filmRest(-380,1000,190),1);assert.equal(m.filmRest(0,0,0),0);});
test('brushing a pinned print gives a bounded swing that grows with speed and distance from the pin',()=>{assert.equal(m.swingKick(0,1),0);assert.ok(m.swingKick(.5,1)>m.swingKick(.5,.3));assert.equal(m.swingKick(50,1),40);assert.equal(m.swingKick(-50,1),-40);assert.equal(m.swingKick(NaN,1),0);});
test('interaction sounds stay silent without an audio context and never throw',()=>{const S=globalThis.Overture.sound;assert.equal(S.enabled,false);assert.equal(S.play('tick'),false);S.set(true);assert.equal(S.play('shutter'),false);S.set(false);assert.deepEqual(S.voices,['tick','shutter','lever','paper','drop','silk','iris','cut']);});
test('a dissolve without a stage still performs its change, exactly once',async()=>{let n=0;await K.dissolve(null,()=>{n++;});assert.equal(n,1);await K.dissolve({},()=>{n++;});assert.equal(n,2);});
