(function(O){
  'use strict';const e=O.escape,icon=O.icon,html=O.html;
  O.define('Wordmark',(p,c)=>html(`<div class="ov-wordmark">${e(p.name||'OVERTURE')}<small>${e(p.tagline||'LIGHT. EMOTION. FORM.')}</small></div>`));
  O.define('TypeSpecimen',(p,c)=>html(`<div class="ov-type-specimen"><p>${e(p.text||'A life in three acts.')}</p><p>用光去观察，用声音去感受，用形式去表达。<br>Bodoni Moda / Manrope / 中文系统字体</p></div>`));
  O.define('PullQuote',(p,c)=>html(`<blockquote class="ov-quote"><p>${e(p.text||'The way you look changes what you see.')}</p><footer>${e(p.source||'OVERTURE · 创作示例文案')}</footer></blockquote>`));
  O.define('Poster',(p,c)=>html(`<figure class="ov-poster"><img src="${e(p.src||O.asset('photos/red-silk.png'))}" alt="红色褶皱时装宣传示例"><figcaption class="ov-poster__type"><strong>${e(p.title||'THE\nRED\nACT').replaceAll('\n','<br>')}</strong><div><small>PHOTOGRAPHY<br>OPERA / FASHION</small><small>OVERTURE<br>视觉示例</small></div></figcaption></figure>`));
  // Two drapes (oxblood and indigo, alternating) close from both wings, the act changes behind them, and they part again.
  O.define('CurtainTransition',(p,c)=>{let act=0,busy=false;const root=html(`<div class="ov-curtain"><h3>Act I. The light.</h3><p>让转场成为内容的一次呼吸。</p><button class="ov-button" type="button">进入下一幕${icon('arrow')}</button><div class="ov-curtain__veil ov-curtain__veil--left" aria-hidden="true"></div><div class="ov-curtain__veil ov-curtain__veil--right" aria-hidden="true"></div></div>`);c.listen(root.querySelector('button'),'click',()=>{if(busy)return;busy=true;root.classList.remove('is-changing');void root.offsetWidth;root.classList.add('is-changing');root.style.setProperty('--veil',act%2?'#601018':'var(--ov-indigo)');root.style.setProperty('--veil-2',act%2?'var(--ov-indigo)':'#601018');O.sound.play('silk',{at:root,gain:.9});c.timeout(()=>{act=(act+1)%3;root.querySelector('h3').textContent=['Act I. The light.','Act II. The voice.','Act III. The form.'][act];c.emit({index:act});},O.reduced()?0:380);c.timeout(()=>{root.classList.remove('is-changing');busy=false;},O.reduced()?1:960);});return root;});

  const loadImage=src=>new Promise((resolve,reject)=>{const image=new Image();image.onload=()=>resolve(image);image.onerror=()=>reject(new Error('素材读取失败，请刷新重试。'));image.src=src;});
  function cover(ctx,image,x,y,w,h,pan=0){const ratio=Math.max(w/image.width,h/image.height),sw=w/ratio,sh=h/ratio,sx=(image.width-sw)*.5+pan*Math.min(image.width-sw,50);ctx.drawImage(image,sx,(image.height-sh)*.5,sw,sh,x,y,w,h);}
  function fit(ctx,text,maxWidth,start,min=20){let size=start;ctx.font=`400 ${size}px "Bodoni Moda", "SimSun", serif`;while(ctx.measureText(text).width>maxWidth&&size>min){size-=2;ctx.font=`400 ${size}px "Bodoni Moda", "SimSun", serif`;}return size;}
  O.define('BrandComposer',(p,c)=>{
    const id=O.uid('brand');let images=null,gpu=null,dirty=true,raf=0,recording=false,recorder=null,recordTimer=null,recordStarted=0,stream=null;
    const settings={title:p.title||'OVERTURE',subtitle:p.subtitle||'Light. Emotion. Form.',mode:'overture',format:'1920x1080',intensity:58};
    const root=html(`<div class="ov-composer"><div class="ov-composer__preview"><canvas aria-label="品牌画面实时预览"></canvas><div class="ov-composer__source" aria-hidden="true" style="position:absolute;inset:0;visibility:hidden;pointer-events:none"></div></div><div class="ov-composer__form"><label class="ov-field"><span>标题</span><input data-field="title" value="${e(settings.title)}" maxlength="40"></label><label class="ov-field"><span>副标题</span><input data-field="subtitle" value="${e(settings.subtitle)}" maxlength="100"></label><label class="ov-field"><span>视觉语言</span><span class="ov-select"><select data-field="mode"><option value="overture">序曲 · 光圈剧场</option><option value="contact">私藏 · 印纸与显影</option><option value="resonance">共鸣 · 褶皱雕塑</option><option value="nocturne">夜场 · 冷光剧场</option></select>${icon('chevron')}</span></label><label class="ov-field"><span>画幅</span><span class="ov-select"><select data-field="format"><option value="1920x1080">横幅 · 1920 × 1080</option><option value="1080x1350">海报 · 1080 × 1350</option><option value="1080x1920">竖屏 · 1080 × 1920</option><option value="1080x1080">方形 · 1080 × 1080</option></select>${icon('chevron')}</span></label><label class="ov-range"><span>动势 / 张力</span><output>58</output><input type="range" data-field="intensity" min="0" max="100" value="58" aria-label="品牌画面动势"></label><div class="ov-composer__actions"><button class="ov-button ov-button--solid" type="button" data-export="png" disabled>${icon('download')}<span>导出 PNG</span></button><button class="ov-button" type="button" data-export="video" disabled>${icon('play')}<span>录制 6 秒</span></button></div><p class="ov-help ov-composer__status" role="status">正在准备本地字体与素材……</p><p class="ov-help">示例素材由 AI 生成。导出在本机完成。动画录制为无声 WebM。</p></div></div>`),canvas=root.querySelector('canvas'),ctx=canvas.getContext('2d'),status=root.querySelector('[role=status]'),png=root.querySelector('[data-export=png]'),video=root.querySelector('[data-export=video]');
    const source=root.querySelector('.ov-composer__source');source.style.minHeight='380px';
    const gpuProxy=O.gpu.mount(source,{type:'silk',src:O.asset('photos/resonance-silk.png'),value:.58,dpr:1},c);gpu=gpuProxy;
    function dimensions(){const [w,h]=settings.format.split('x').map(Number);if(canvas.width!==w||canvas.height!==h){canvas.width=w;canvas.height=h;}}
    function paint(now=0){
      if(!images)return;dimensions();const w=canvas.width,h=canvas.height,pad=w*.047,portrait=h>w,t=now/1000;
      const light=settings.mode==='contact',ink=light?'#201810':settings.mode==='nocturne'?'#ecf0f6':'#f1ebdf';ctx.fillStyle=light?'#eee8dc':settings.mode==='nocturne'?'#0a0f1f':'#090706';ctx.fillRect(0,0,w,h);
      if(settings.mode==='overture'){
        cover(ctx,images.overture,0,0,w,h,Math.sin(t*.22)*.25*(settings.intensity/100));
        ctx.fillStyle='rgba(0,0,0,.12)';ctx.fillRect(0,0,w,h);
      }else if(settings.mode==='nocturne'){
        // Nocturne: the opera plate re-lit by cold light, a warm follow-spot kept at its centre.
        cover(ctx,images.overture,0,0,w,h,Math.sin(t*.22)*.25*(settings.intensity/100));ctx.save();ctx.globalCompositeOperation='color';ctx.globalAlpha=.78;ctx.fillStyle='#2a4488';ctx.fillRect(0,0,w,h);ctx.globalAlpha=1;ctx.globalCompositeOperation='multiply';ctx.fillStyle='#9aa8d4';ctx.fillRect(0,0,w,h);ctx.restore();
        const cx=w*.59,cy=h*.55,r=Math.min(w,h)*(.2+settings.intensity/400);const g=ctx.createRadialGradient(cx,cy,r*.1,cx,cy,r);g.addColorStop(0,'rgba(255,206,156,.55)');g.addColorStop(1,'rgba(255,214,168,0)');ctx.save();ctx.globalCompositeOperation='screen';ctx.fillStyle=g;ctx.fillRect(0,0,w,h);ctx.restore();
        ctx.strokeStyle='rgba(157,188,255,.8)';ctx.lineWidth=Math.max(1,w*.0012);ctx.beginPath();ctx.arc(cx,cy,r*1.05,0,Math.PI*2);ctx.stroke();ctx.fillStyle='rgba(10,15,31,.18)';ctx.fillRect(0,0,w,h);
      }else if(settings.mode==='contact'){
        ctx.save();ctx.translate(w*.5,h*.55);ctx.rotate(-.1);ctx.fillStyle='#16110d';ctx.fillRect(-w*.65,-h*.13,w*1.3,h*.27);
        [images.backstage,images.bow,images.red,images.runway].forEach((im,i)=>{ctx.save();ctx.filter='grayscale(1)';cover(ctx,im,-w*.59+i*w*.3,-h*.11,w*.28,h*.22);ctx.restore();});ctx.restore();
        const iw=portrait?w*.70:w*.36,ih=portrait?h*.43:h*.58,x=portrait?w*.18:w*.53,y=portrait?h*.37:h*.32;ctx.save();ctx.translate(x+iw/2,y+ih/2);ctx.rotate(.075);ctx.fillStyle='#faf3e8';ctx.shadowColor='rgba(24,12,4,.22)';ctx.shadowBlur=24;ctx.shadowOffsetY=14;ctx.fillRect(-iw/2-10,-ih/2-10,iw+20,ih+45);ctx.shadowColor='transparent';cover(ctx,images.red,-iw/2,-ih/2,iw,ih,Math.sin(t*.2)*.1);ctx.restore();
      }else{
        const scene=gpu.engine?.canvas,art=scene&&gpu.state.backend!=='static'&&source.classList.contains('is-gpu-ready')?scene:images.silk;const areaH=h*(portrait?.60:.76),scale=Math.min(w/art.width,areaH/art.height);ctx.drawImage(art,(w-art.width*scale)/2,h*(portrait?.24:.14)+(areaH-art.height*scale)/2,art.width*scale,art.height*scale);
      }
      ctx.fillStyle=ink;ctx.textBaseline='alphabetic';ctx.font=`400 ${Math.max(12,w*.008)}px "Manrope", sans-serif`;ctx.fillText('PHOTOGRAPHY / OPERA / FASHION',pad,pad);
      const size=fit(ctx,settings.title||'OVERTURE',w-pad*2,portrait?w*.19:w*.171,w*.035);ctx.fillText(settings.title||'OVERTURE',pad,pad+size*1.04);
      ctx.font=`400 ${w*.014}px "Manrope", "Microsoft YaHei", sans-serif`;const subtitle=settings.subtitle;const subY=portrait?pad+size*1.40:pad+size*1.42;fitSans(subtitle,w-pad*2,w*.014);ctx.fillText(subtitle,pad,subY);
      ctx.strokeStyle=ink;ctx.lineWidth=Math.max(.8,w*.0007);ctx.beginPath();ctx.moveTo(pad,h-pad*1.25);ctx.lineTo(w-pad,h-pad*1.25);ctx.stroke();
      ctx.font=`400 ${w*.009}px "Manrope", sans-serif`;ctx.fillText('OVERTURE / STUDIO',pad,h-pad*.65);ctx.textAlign='right';ctx.fillText('LIGHT. EMOTION. FORM.',w-pad,h-pad*.65);ctx.textAlign='left';
      dirty=false;
    }
    function fitSans(text,width,start){let size=start;ctx.font=`400 ${size}px "Manrope", "Microsoft YaHei", sans-serif`;while(ctx.measureText(text).width>width&&size>8){size-=.5;ctx.font=`400 ${size}px "Manrope", "Microsoft YaHei", sans-serif`;}}
    // A new format morphs the preview from its old frame; a new visual language develops in.
    root.querySelectorAll('[data-field]').forEach(input=>c.listen(input,'input',()=>{const name=input.dataset.field;const before=name==='format'&&images?canvas.getBoundingClientRect():null;settings[name]=name==='intensity'?+input.value:input.value;if(name==='intensity'){root.querySelector('output').value=input.value;gpu.setValue(input.value/100);}dirty=true;if(before){paint(performance.now());const after=canvas.getBoundingClientRect();if(!O.reduced()&&after.width&&after.height)canvas.animate([{transform:`translate(${before.left-after.left}px,${before.top-after.top}px) scale(${before.width/after.width},${before.height/after.height})`,transformOrigin:'0 0'},{transform:'none',transformOrigin:'0 0'}],{duration:O.motion.time('settle'),easing:O.motion.easing('settle')});O.sound.play('paper',{at:canvas});}if(name==='mode'&&images){paint(performance.now());O.motion.develop(canvas,{duration:700});O.sound.play('paper',{at:canvas});}c.emit({settings:{...settings}});}));
    function loop(now){if(!c.alive)return;raf=requestAnimationFrame(loop);if(document.hidden&&!recording)return;if(dirty||recording||settings.mode==='resonance'&&!O.reduced())paint(now);}
    Promise.all([loadImage(O.asset('photos/overture-art.png')),loadImage(O.asset('photos/red-silk.png')),loadImage(O.asset('photos/hero-backstage.jpg')),loadImage(O.asset('photos/stage-bow.jpg')),loadImage(O.asset('photos/runway.jpg')),loadImage(O.asset('photos/resonance-silk.png')),document.fonts.load('40px "Bodoni Moda"'),document.fonts.load('16px "Manrope"')]).then(([overture,red,backstage,bow,runway,silk])=>{if(!c.alive)return;images={overture,red,backstage,bow,runway,silk};png.disabled=false;video.disabled=!window.MediaRecorder||!canvas.captureStream;status.textContent='可以开始创作。导出尺寸与所选画幅一致。';if(video.disabled)status.textContent+=' 此浏览器仅支持 PNG 导出。';paint();raf=requestAnimationFrame(loop);}).catch(err=>{status.textContent=err.message;});
    c.listen(png,'click',()=>{paint(performance.now());O.sound.play('shutter',{at:png});canvas.toBlob(blob=>{if(!c.alive)return;if(!blob){status.textContent='图片导出失败，请重试。';return;}O.download(blob,`overture-${settings.mode}-${settings.format}.png`);status.textContent=`PNG 已生成，已启动下载（${settings.format}）。`;c.emit({exported:'png',width:canvas.width,height:canvas.height});},'image/png');});
    c.listen(video,'click',()=>{
      if(recording){recorder?.stop();return;}
      const mime=['video/webm;codecs=vp9','video/webm;codecs=vp8','video/webm'].find(v=>MediaRecorder.isTypeSupported(v));if(!mime){status.textContent='此浏览器不支持 WebM 录制，请使用 PNG 导出。';return;}
      try{
        stream=canvas.captureStream(30);recorder=new MediaRecorder(stream,{mimeType:mime,videoBitsPerSecond:8000000});const chunks=[];const filename=`overture-${settings.mode}-${settings.format}.webm`;recording=true;recordStarted=performance.now();png.disabled=true;root.querySelectorAll('[data-field]').forEach(x=>x.disabled=true);video.querySelector('span').textContent='结束录制';status.textContent='正在录制 6 秒，请保持此页面可见。';
        recorder.ondataavailable=ev=>{if(ev.data.size)chunks.push(ev.data);};
        recorder.onstop=()=>{recording=false;clearTimeout(recordTimer);stream?.getTracks().forEach(t=>t.stop());stream=null;if(!c.alive)return;png.disabled=false;root.querySelectorAll('[data-field]').forEach(x=>x.disabled=false);video.querySelector('span').textContent='录制 6 秒';const duration=(performance.now()-recordStarted)/1000;if(chunks.length){O.download(new Blob(chunks,{type:'video/webm'}),filename);status.textContent=`已生成 ${duration.toFixed(1)} 秒无声 WebM。`;c.emit({exported:'webm',duration});}else status.textContent='没有录制到画面，请重试。';};
        recorder.onerror=()=>{status.textContent='录制中断，请改用 PNG 导出。';if(recorder.state!=='inactive')recorder.stop();};recorder.start(250);recordTimer=setTimeout(()=>{if(recorder.state!=='inactive')recorder.stop();},6000);
      }catch(err){recording=false;status.textContent='无法开始录制：'+err.message;stream?.getTracks().forEach(t=>t.stop());png.disabled=false;root.querySelectorAll('[data-field]').forEach(x=>x.disabled=false);}
    });
    c.cleanup(()=>{cancelAnimationFrame(raf);clearTimeout(recordTimer);if(recorder?.state==='recording')recorder.stop();stream?.getTracks().forEach(t=>t.stop());});
    root.ovComposer={settings,paint,canvas};return root;
  });
})(globalThis.Overture);
