// Single source for the live library, component cards and usage documentation.
export const components = [
  {
    "name": "CueButton",
    "title": "进入按钮",
    "group": "动作与导航",
    "description": "圆形或长条按钮，以快门闭合回应确认，支持异步操作的忙碌与失败反馈。",
    "subtitle": "进入按钮",
    "usage": "主要动作、进入下一幕、提交本地操作。",
    "states": "悬停、键盘聚焦、禁用、忙碌和完成。1.3：填充从指针进入处张开，按压 snap 回弹；可选快门声。",
    "api": "label, variant:'circle', disabled, onActivate。",
    "height": 220,
    "wide": false
  },
  {
    "name": "IconButton",
    "title": "图标按钮",
    "group": "动作与导航",
    "description": "以单一细线图标表达可反复切换的动作。",
    "subtitle": "图标按钮",
    "usage": "收藏、锁定、静音等可逆动作。",
    "states": "aria-pressed 双态、焦点、禁用。1.3：悬停填充从指针处张开，按下时图标像印章压下。",
    "api": "label, icon, value, disabled；setValue(boolean)。",
    "height": 180,
    "wide": false
  },
  {
    "name": "TextLink",
    "title": "文字链接",
    "group": "动作与导航",
    "description": "细规则线与箭头形成不抢占图像的次级入口。",
    "subtitle": "文字链接",
    "usage": "阅读更多、查看说明、进入详情。",
    "states": "悬停、焦点；提供 href 时为真实导航。",
    "api": "label, href；不提供 href 时为示例状态。",
    "height": 180,
    "wide": false
  },
  {
    "name": "StageTabs",
    "title": "幕次标签页",
    "group": "动作与导航",
    "description": "朱红取景框是一个弹簧：按速度拉长、带轻微过冲落定；面板按切换方向展开。",
    "subtitle": "幕次标签页",
    "usage": "同一上下文中的内容切换。",
    "states": "选中、非选中；左右、Home、End 键；原生 tablist 语义。连续切换保留取景框速度；减少动态时直接落位。",
    "api": "items, panels, label；setValue(index)。",
    "height": 290,
    "wide": false
  },
  {
    "name": "ChapterNav",
    "title": "章节导航",
    "group": "动作与导航",
    "description": "有顺序意义的章号成为阅读位置标记。",
    "subtitle": "章节导航",
    "usage": "分幕长页、作品集章节。",
    "states": "当前步骤、聚焦；onSelect 交给应用导航。1.3：朱红下划线按前进方向接力。",
    "api": "items, onSelect(index)。",
    "height": 180,
    "wide": false
  },
  {
    "name": "Breadcrumb",
    "title": "路径导航",
    "group": "动作与导航",
    "description": "用细线方向标记说明当前层级。",
    "subtitle": "路径导航",
    "usage": "档案、作品详情和分类页。",
    "states": "当前位置 aria-current；示例链接发出选择事件。",
    "api": "items；ov:change 的 value 为所选层级。",
    "height": 180,
    "wide": false
  },
  {
    "name": "Pagination",
    "title": "翻页",
    "group": "动作与导航",
    "description": "像翻阅底片页一样浏览有限集合。",
    "subtitle": "翻页",
    "usage": "分页作品、资料清单。",
    "states": "首末页禁用、页码播报、按钮焦点。1.3：页码按翻页方向翻片。",
    "api": "total, size；setValue(page)，事件含起止索引。",
    "height": 180,
    "wide": false
  },
  {
    "name": "CommandPalette",
    "title": "动作搜索",
    "group": "动作与导航",
    "description": "集中寻找动作，保留可见结果和键盘路径。",
    "subtitle": "动作搜索",
    "usage": "工具密集页面的快捷导航。",
    "states": "搜索、有结果、空结果、当前结果、执行、关闭。1.3：从触发按钮以光圈张开并退回；结果逐项显影（最多六项）；Escape 同样有退场。",
    "api": "actions:[{label,value}], onSelect；上下键/Enter/Escape。",
    "height": 230,
    "wide": false
  },
  {
    "name": "TextField",
    "title": "文字输入",
    "group": "表单与选择",
    "description": "取景角与底线强调输入焦点；错误贴近字段。",
    "subtitle": "文字输入",
    "usage": "邮箱、姓名和短文本。",
    "states": "空、输入、聚焦、禁用、错误、纠正。1.3：出错时朱红线从左侧曝光，提示文字显影。",
    "api": "type, label, value, placeholder, help, error, required, disabled。",
    "height": 250,
    "wide": false
  },
  {
    "name": "TextArea",
    "title": "创作笔记",
    "group": "表单与选择",
    "description": "多行文字与字数余量，让长表达仍保持简洁。",
    "subtitle": "创作笔记",
    "usage": "说明、创作手记、反馈。",
    "states": "空、输入、长度上限、可调整高度。",
    "api": "label, value, placeholder, maxLength；setValue(text)。",
    "height": 300,
    "wide": false
  },
  {
    "name": "Select",
    "title": "下拉选择",
    "group": "表单与选择",
    "description": "采用原生选择行为，统一底线和方向标记。",
    "subtitle": "下拉选择",
    "usage": "有限选项，移动端调用系统选择器。",
    "states": "聚焦、展开、选定。",
    "api": "items, label；setValue(value)。",
    "height": 200,
    "wide": false
  },
  {
    "name": "ChoiceGroup",
    "title": "单选组",
    "group": "表单与选择",
    "description": "相纸从轮廓变为实色，清楚表明互斥选择。",
    "subtitle": "单选组",
    "usage": "视觉主题、输出类型、有限方案。",
    "states": "选中、未选中、键盘方向键。1.3：选中压印从指针进入处张开。",
    "api": "items, label；事件含 index 与 value。",
    "height": 220,
    "wide": false
  },
  {
    "name": "Check",
    "title": "复选框",
    "group": "表单与选择",
    "description": "精确的直角边框与短促落位的确认标记。",
    "subtitle": "复选框",
    "usage": "多选、偏好、局部开关。",
    "states": "选中、未选中、禁用、聚焦。1.3：勾一笔画出，方框以 snap 弹簧转正。",
    "api": "label, value, disabled；setValue(boolean)。",
    "height": 170,
    "wide": false
  },
  {
    "name": "Switch",
    "title": "状态开关",
    "group": "表单与选择",
    "description": "机械拨杆露出朱红状态窗，让开关像相机上的实体动作一样明确。",
    "subtitle": "状态开关",
    "usage": "立即生效的偏好设置。",
    "states": "开、关、禁用；Space/Enter。1.3：拨杆以 snap 弹簧带轻微过冲落位，按住时下压；可选拨杆声。",
    "api": "label, value, disabled；setValue(boolean)。",
    "height": 170,
    "wide": false
  },
  {
    "name": "Range",
    "title": "曝光滑杆",
    "group": "表单与选择",
    "description": "镜头式刻度与朱红游标表达连续数值；游标像表针一样带质量跟随，保留原生滑杆与键盘调节。",
    "subtitle": "曝光滑杆",
    "usage": "曝光、音量、开度、材质强度。",
    "states": "拖拽、聚焦、键盘、最小最大、数值输出。游标跟随为视觉，数值输出始终精确；越过刻度有齿感声（可选）。",
    "api": "min, max, step, value, label, unit；setValue(number)。",
    "height": 210,
    "wide": false
  },
  {
    "name": "Stepper",
    "title": "数量步进",
    "group": "表单与选择",
    "description": "翻片式数字窗口配合有边界的加减，立即回应数量或底片切换。",
    "subtitle": "数量步进",
    "usage": "印刷份数、数量、分段级别。",
    "states": "值变化、边界禁用、屏幕阅读器播报。1.3：翻片按增减方向转动。",
    "api": "min, max, value, label；setValue(number)。",
    "height": 180,
    "wide": false
  },
  {
    "name": "TagInput",
    "title": "关键词输入",
    "group": "表单与选择",
    "description": "把文本整理成可以单独移除的校样标签。",
    "subtitle": "关键词输入",
    "usage": "作品关键词、有限标签。",
    "states": "输入、去重、添加、移除、数量上限。1.3：新词显影出现，删去的词被裁掉，其余词 FLIP 到新位置。",
    "api": "value, label；Enter/逗号添加，Backspace 移除。",
    "height": 250,
    "wide": false
  },
  {
    "name": "Dropzone",
    "title": "本地图片选择",
    "group": "表单与选择",
    "description": "文件进入取景框；仅在本机预览和验证。",
    "subtitle": "本地图片选择",
    "usage": "导入 PNG、JPEG、WebP 图片。",
    "states": "空、拖入、选择、成功、格式错误、超大文件。1.3：选中的图片显影进入。",
    "api": "10 MB 上限，支持文件选择键盘入口，销毁时释放对象 URL。",
    "height": 360,
    "wide": false
  },
  {
    "name": "Accordion",
    "title": "折叠说明",
    "group": "浮层与披露",
    "description": "用展开动作分配说明文字的阅读深度。",
    "subtitle": "折叠说明",
    "usage": "FAQ、规范、设置分组。",
    "states": "关闭、展开、原生 details/summary 键盘行为。1.3：展开与收起都有高度过渡，正文淡入淡出（浏览器支持 interpolate-size 时）。",
    "api": "items:[[title,body]]；事件含 index/open。",
    "height": 390,
    "wide": false
  },
  {
    "name": "Dialog",
    "title": "确认对话框",
    "group": "浮层与披露",
    "description": "幕布暂时退暗，给需要确认的当前动作完整焦点。",
    "subtitle": "确认对话框",
    "usage": "需要中断和保护焦点的编辑确认。",
    "states": "打开、取消、Escape、校验、保存、焦点返回。1.3：从触发按钮以光圈张开；按钮、取消、Escape、遮罩、保存五条路径都先退回按钮再关闭；遮罩淡入淡出。",
    "api": "label, title；原生 dialog；示例保存只作用于页面。",
    "height": 230,
    "wide": false
  },
  {
    "name": "Drawer",
    "title": "侧边编辑",
    "group": "浮层与披露",
    "description": "展开侧幕编辑说明，仍保留原作品的上下文。",
    "subtitle": "侧边编辑",
    "usage": "短表单、作品信息、局部编辑。",
    "states": "打开、编辑、保存、取消、关闭。1.3：侧幕以 settle 弹簧滑入，内容稍后跟上；任何关闭方式都滑出。",
    "api": "label, title；原生模态焦点，移动端适配屏幕宽度。",
    "height": 230,
    "wide": false
  },
  {
    "name": "Tooltip",
    "title": "辅助提示",
    "group": "浮层与披露",
    "description": "悬停和键盘聚焦时提供简短的动作说明。",
    "subtitle": "辅助提示",
    "usage": "解释图标；必要信息不可只放提示内。",
    "states": "悬停、聚焦、离开；aria-describedby。",
    "api": "text；不装载复杂交互内容。",
    "height": 180,
    "wide": false
  },
  {
    "name": "Popover",
    "title": "就地选项",
    "group": "浮层与披露",
    "description": "在触发点旁展开少量设置，不打断页面。",
    "subtitle": "就地选项",
    "usage": "取景、筛选与局部偏好。",
    "states": "展开、关闭、外部点击、Escape、选项改变。1.3：从触发按钮张开，关闭时先折回再隐藏。",
    "api": "示例包含两个原生复选框；事件含 option/value。",
    "height": 330,
    "wide": false
  },
  {
    "name": "Toast",
    "title": "可撤销反馈",
    "group": "反馈与进度",
    "description": "像显影后的印记一样确认动作，并提供撤销。",
    "subtitle": "可撤销反馈",
    "usage": "轻量、可逆的操作结果。",
    "states": "出现、撤销、关闭、超时；悬停/聚焦时保留。1.3：快门式出现与消失；底部细线显示剩余时间，悬停或聚焦时暂停并在离开后继续。",
    "api": "示例收藏只保存在组件状态；role=status。",
    "height": 240,
    "wide": false
  },
  {
    "name": "Notice",
    "title": "状态提示",
    "group": "反馈与进度",
    "description": "朱红细线指出需要关注的状态，并给出恢复动作。",
    "subtitle": "状态提示",
    "usage": "可恢复错误、缺少素材、下一步说明。",
    "states": "待处理、执行恢复动作、已解决。1.3：解决后内容显影。",
    "api": "title, message, action；使用文字而不只依赖颜色。",
    "height": 250,
    "wide": false
  },
  {
    "name": "Progress",
    "title": "显影进度",
    "group": "反馈与进度",
    "description": "Expose、Develop、Fix 三个过程映射可见进度。",
    "subtitle": "显影进度",
    "usage": "明确总量的任务；也可由外部真实进度驱动。",
    "states": "开始、暂停、继续、完成、重置。1.3：每步 4 % 由 settle 弹簧连成连续推进，运行时前沿有冷光。",
    "api": "value；setValue(0..100)。默认是有明确标识的进度示例。",
    "height": 280,
    "wide": false
  },
  {
    "name": "Loading",
    "title": "准备状态",
    "group": "反馈与进度",
    "description": "缓慢转动的光圈配合内容骨架。",
    "subtitle": "准备状态",
    "usage": "等待素材或内容的短暂状态。",
    "states": "加载、减少动态；状态有文字说明。",
    "api": "label；这是展示加载态的组件，完成时由宿主移除。",
    "height": 190,
    "wide": false
  },
  {
    "name": "EmptyState",
    "title": "空白起点",
    "group": "反馈与进度",
    "description": "空的取景框告诉用户缺少什么、可以怎样开始。",
    "subtitle": "空白起点",
    "usage": "初次使用、没有作品或搜索无结果。",
    "states": "空、添加示例、成功。1.3：加入的照片展开并显影。",
    "api": "title, message；默认动作加入一个本地示例。",
    "height": 370,
    "wide": false
  },
  {
    "name": "EditorialTable",
    "title": "档案表格",
    "group": "内容与数据",
    "description": "编辑档案般的细线表格，支持有意义的排序。",
    "subtitle": "档案表格",
    "usage": "作品清单、批次与状态。",
    "states": "默认、排序升降、行悬停、表头语义。1.3：排序时同一行 FLIP 到新位置，排序箭头翻转。",
    "api": "rows:[{title,category,frames,state}]。",
    "height": 360,
    "wide": true
  },
  {
    "name": "Timeline",
    "title": "幕次时间线",
    "group": "内容与数据",
    "description": "舞台提示单的时间和事件组成清楚的顺序。",
    "subtitle": "幕次时间线",
    "usage": "活动安排、制作过程、作品历程。",
    "states": "顺序语义；每项都有时间、标题、补充说明。",
    "api": "items:[[time,title,description]]。",
    "height": 290,
    "wide": false
  },
  {
    "name": "ApertureStage",
    "title": "光圈舞台",
    "group": "影像与 GPU",
    "description": "由原始图像资产与 GPU 采样、开度遮罩和视差共同组成。",
    "subtitle": "光圈舞台",
    "usage": "整页开幕、品牌片头、进入作品。",
    "states": "开度调节、鼠标视差、进入/退回、静态降级。1.3：开度由 stage 弹簧驱动（约 0.83 s），滑杆与滚动联动 snap／settle 跟随，视差带惯性。",
    "api": "chrome, value；setValue(0..100)。照片底图不是完整三维剧院。",
    "height": 520,
    "wide": true
  },
  {
    "name": "ContactSheet",
    "title": "底片档案",
    "group": "影像与 GPU",
    "description": "底片与齿孔自动循环走片，焦点逐帧移动；照片、相纸边框、题名和套准标记共同换位。",
    "subtitle": "底片档案",
    "usage": "作品浏览、系列筛选、图像选择。",
    "states": "自动循环、暂停/继续、悬停/聚焦停格、离屏暂停、键盘与减少动态。1.3：底片带 1:1 跟手拖动，甩出后按速度停在最近一帧（settle 弹簧承接速度）。",
    "api": "items:[[file,title,category]], autoplay:true, interval:4800, index:0；setValue(index)。自动播放不播报 live region，不移动键盘焦点。",
    "height": 700,
    "wide": true
  },
  {
    "name": "FlashlightFocus",
    "title": "追光取景",
    "group": "影像与 GPU",
    "description": "整面六张照片墙固定可见；每三格滚轮切换一张，光束只停在六张照片中心。",
    "subtitle": "移动光，发现细节",
    "usage": "摄影作品浏览、品牌视觉探索、局部内容发现。",
    "states": "三格一张、0/3 至 2/3 计数、固定灯位、反向重计、首尾释放滚动、触屏/键盘逐张切换、独立开度、GPU / CSS 降级。1.3：前两格转动准星（对焦环）；第三格光束沿 settle 弹簧移到下一张照片中心，途中收窄、到达张开，只在六个固定灯位停留；减少动态时淡出淡入；指针拂过相纸时绕图钉摆动。",
    "api": "mode:'contained'|'page', value:25, items:[[file,title,category]]；setValue(0..100) 调整开度；ov:change 返回 x,y,value,index,progress,pending。",
    "height": 770,
    "wide": true
  },
  {
    "name": "PinnedPhotoWall",
    "title": "红线照片墙",
    "group": "影像与 GPU",
    "description": "固定大光束照在中央，每两格滚轮推动一张照片经过视野；第一格蓄势，第二格运镜落位。",
    "subtitle": "光留在这里，记忆向前",
    "usage": "视觉档案、作品故事、品牌时间线、全屏滚动叙事。",
    "states": "两格一张、半步反馈、可打断运镜、首尾释放滚动、索引/键盘/触屏切换、减少动态直接落位。1.3：运镜由 stage 弹簧驱动，连续输入保留速度；移动时镜头略后退，到达时推近；计数翻片；减少动态时淡出淡入到下一张；相纸被拂过时绕图钉摆动。",
    "api": "mode:'contained'|'page', items:[[file,title,category]]；setValue(index) 切换照片；ov:change 返回 index,progress,pending。page 使用一屏高度；触控板小输入累计为两格。",
    "height": 770,
    "wide": true
  },
  {
    "name": "FilmCanister",
    "title": "胶卷暗盒",
    "group": "影像与 GPU",
    "description": "三维 35 mm 暗盒里拉出一卷胶片：横向拖动拉出或卷回，卷轴随之转动；把一帧向下拖出，它会作为相纸落到桌面并显影。",
    "subtitle": "拉出胶片，拖出一帧",
    "usage": "作品集入口、系列浏览、从一组照片中挑选并收藏若干张。",
    "states": "拖动／滚轮／方向键拉片，放手后带惯性；悬停冷光取景并显色；向下拖出成相纸，未到桌面则弹回原位；桌面相纸可拖动摆放，双击、回车或退格放回胶片；空位显示为透明片基；WebGPU / WebGL2 暗盒与 CSS 静态暗盒降级；减少动态时无惯性、无显影动画。1.3：拉过两端有橡皮筋阻力并回弹，甩到尽头会弹回；相纸落桌以 settle 弹簧定位、snap 弹簧转正，并有一次落地压缩；方向键拉片走弹簧。",
    "api": "items:[[file,title,category]], roll:'ROLL 01', dates:'FEB 2026 — JUN 2026', pulled:3.2（初始拉出帧数）；setValue(0..100) 设置拉出长度；ov:change 返回 pull、turn、out（已冲印的帧序号）。",
    "height": 820,
    "wide": true
  },
  {
    "name": "DevelopImage",
    "title": "局部显影",
    "group": "影像与 GPU",
    "description": "GPU 让光斑附近从黑白显影为彩色：光斑带惯性跟随、进出时张缩；选中时显影液从按下的点漫开到整幅。",
    "subtitle": "局部显影",
    "usage": "照片预览、可选择的视觉内容。",
    "states": "移动显影、键盘聚焦从中心漫开、选中/取消、降级。1.3：光斑、漫开都由弹簧驱动，漫开前沿有暖色显影线。",
    "api": "src, alt, caption, label；aria-pressed 表示选中。",
    "height": 430,
    "wide": false
  },
  {
    "name": "FocusGallery",
    "title": "取景画廊",
    "group": "影像与 GPU",
    "description": "网格图像经聚焦显影后，进入独立的大图阅读。",
    "subtitle": "取景画廊",
    "usage": "摄影、时装作品或演出档案。",
    "states": "悬停、聚焦、放大、前后翻图、Escape 关闭。1.3：打开时照片从缩略图飞到灯箱并显影，关闭时飞回原位；翻页按方向滑入并显影。",
    "api": "items；原生 dialog 和焦点返回；左右键翻图。",
    "height": 510,
    "wide": true
  },
  {
    "name": "CompareLens",
    "title": "显影比较",
    "group": "影像与 GPU",
    "description": "同一图像的黑白和彩色由一条可控分界线比较。",
    "subtitle": "显影比较",
    "usage": "前后对比、调色说明、工艺变化。",
    "states": "拖拽、键盘、分界值说明。1.3：分界线以 snap 弹簧跟随。",
    "api": "src；setValue(0..100)；原生 range 控制。",
    "height": 420,
    "wide": false
  },
  {
    "name": "SilkResonance",
    "title": "共振褶皱",
    "group": "影像与 GPU",
    "description": "透明织物图像映射到细分曲面；张力是一根轻阻尼弹簧，松手后带着速度回荡，凝住会停在回荡中途。",
    "subtitle": "共振褶皱",
    "usage": "品牌主视觉、交互雕塑、参数化艺术。",
    "states": "拖动、张力、键盘、持续运动、凝住、下载、降级。1.3：resonance 弹簧（k 140 · c 3.2，周期 0.53 s）；凝住冻结位移与速度，继续时同一次回荡接着走。",
    "api": "value, chrome；setValue(0..100)；WebGPU 优先、WebGL2 回退。",
    "height": 610,
    "wide": true
  },
  {
    "name": "CuePlayer",
    "title": "共振播放器",
    "group": "影像与 GPU",
    "description": "三音合成声音片段让声响、时间线和播放状态相连。",
    "subtitle": "共振播放器",
    "usage": "声音作品入口；这里只提供原创合成音色示意。",
    "states": "播放、暂停、续播、拖动进度、静音、结束。",
    "api": "默认 12 秒，不自动播放；组件销毁时关闭 AudioContext。",
    "height": 250,
    "wide": false
  },
  {
    "name": "Wordmark",
    "title": "品牌字标",
    "group": "品牌与版式",
    "description": "大尺度高对比衬线字标，配合克制的落款。",
    "subtitle": "品牌字标",
    "usage": "页首、封面与品牌署名。",
    "states": "响应式缩放；保持足够留白。",
    "api": "name, tagline；默认名称是本体系工作名。",
    "height": 270,
    "wide": false
  },
  {
    "name": "TypeSpecimen",
    "title": "字体编排",
    "group": "品牌与版式",
    "description": "展示标题与中文正文共同工作的比例。",
    "subtitle": "字体编排",
    "usage": "建立跨语言的标题／正文层级。",
    "states": "长标题换行、窄屏缩放。",
    "api": "text；字体本地托管，中文使用本机字库。",
    "height": 250,
    "wide": false
  },
  {
    "name": "PullQuote",
    "title": "编辑引言",
    "group": "品牌与版式",
    "description": "以字的尺度和细线署名建立段落停顿。",
    "subtitle": "编辑引言",
    "usage": "作品宣言、导语、创作观点。",
    "states": "blockquote 与署名语义。",
    "api": "text, source；默认文字明确为创作示例。",
    "height": 280,
    "wide": false
  },
  {
    "name": "Poster",
    "title": "宣传海报",
    "group": "品牌与版式",
    "description": "图像全幅与大字叠合的直幅品牌版式。",
    "subtitle": "宣传海报",
    "usage": "海报、社交封面、系列封面。",
    "states": "静态版式，标题与图像可替换。",
    "api": "title（换行支持）, src。",
    "height": 630,
    "wide": false
  },
  {
    "name": "BrandComposer",
    "title": "品牌工坊",
    "group": "品牌与版式",
    "description": "同一视觉体系内编辑内容、画幅、动势并导出。",
    "subtitle": "品牌工坊",
    "usage": "网页横幅、竖幅海报、方形品牌宣传。",
    "states": "编辑、画幅/场景切换、PNG、6 秒 WebM、错误反馈。1.3：换画幅时预览从旧画框变形到新画框，换视觉语言时显影。",
    "api": "title, subtitle；导出全在本机，无网络上传。",
    "height": 840,
    "wide": true
  },
  {
    "name": "CurtainTransition",
    "title": "幕布转场",
    "group": "品牌与版式",
    "description": "深红与深蓝两幅幕布从两侧合拢，换幕后分开，避免无意义的漂浮。",
    "subtitle": "幕布转场",
    "usage": "有顺序的页面或叙事段落切换。",
    "states": "当前幕、转场、下一幕；减少动态时立即切换。",
    "api": "示例三幕循环；状态变化通过 ov:change 传递。",
    "height": 300,
    "wide": false
  }
];
