(function(O){
  'use strict';
  const e=O.escape, icon=O.icon, html=O.html, M=O.motion, S=O.sound;
  function button(label, cls='', symbol='arrow'){return `<button type="button" class="ov-button ${cls}"><span>${e(label)}</span>${symbol?icon(symbol):''}</button>`;}
  O.define('CueButton',(p,c)=>{
    const root=html(`<div class="ov-demo-actions">${button(p.label||'进入这一幕',p.variant==='circle'?'ov-button--circle':'')}<span class="ov-help" aria-live="polite"></span></div>`), b=root.querySelector('button'), out=root.querySelector('.ov-help');
    if(p.disabled)b.disabled=true;b.classList.add('ov-cue-shutter');let exposeTimer=0;c.cleanup(()=>clearTimeout(exposeTimer));
    c.listen(b,'pointermove',ev=>{const r=b.getBoundingClientRect();b.style.setProperty('--x',`${ev.clientX-r.left}px`);b.style.setProperty('--y',`${ev.clientY-r.top}px`);});
    c.listen(b,'click',async()=>{b.classList.remove('is-exposing');void b.offsetWidth;b.classList.add('is-exposing');S.play('shutter',{at:b});clearTimeout(exposeTimer);exposeTimer=setTimeout(()=>b.classList.remove('is-exposing'),680);if(p.onActivate){b.disabled=true;b.setAttribute('aria-busy','true');try{await p.onActivate();c.emit({activated:true});}catch(error){out.textContent=error.message||'这次操作未完成，请重试。';}finally{if(c.alive){b.disabled=false;b.removeAttribute('aria-busy');}}return;} b.disabled=true;b.setAttribute('aria-busy','true');b.querySelector('span').textContent='正在开幕';c.timeout(()=>{b.disabled=false;b.removeAttribute('aria-busy');b.querySelector('span').textContent=p.label||'再次进入';out.textContent='这一幕已就绪';M.develop(out,{duration:520});c.emit({activated:true});},650);});return root;
  });
  O.define('IconButton',(p,c)=>{const root=html(`<button type="button" class="ov-icon-button" aria-label="${e(p.label||'收藏这一帧')}" aria-pressed="false">${icon(p.icon||'bookmark')}</button>`);let value=!!p.value;const set=(v,touched)=>{value=!!v;root.setAttribute('aria-pressed',String(value));if(touched){S.play('tick',{at:root,pitch:value?1.1:.85});if(value)M.imprint(root.querySelector('svg'));}c.emit({value});};c.listen(root,'click',()=>set(!value,true));c.setValue=set;set(value);return root;});
  O.define('TextLink',(p,c)=>{const root=html(`<a class="ov-text-link" href="${e(p.href||'#')}"><span>${e(p.label||'展开创作手记')}</span>${icon('arrow')}</a>`);if(!p.href)c.listen(root,'click',ev=>{ev.preventDefault();root.querySelector('span').textContent='手记已加入阅读列表';M.develop(root.querySelector('span'),{duration:520});c.emit({activated:true});});return root;});
  O.define('StageTabs',(p,c)=>{
    const values=p.items||['摄影','歌剧','时装'], id=O.uid('tabs');let current=0;
    const root=html(`<div class="ov-tabs"><div role="tablist" aria-label="${e(p.label||'创作领域')}">${values.map((v,i)=>`<button type="button" role="tab" id="${id}-t${i}" aria-controls="${id}-p${i}" aria-selected="${i===0}" tabindex="${i===0?0:-1}">${e(v)}</button>`).join('')}<i class="ov-tabs__line"></i></div>${values.map((v,i)=>`<div role="tabpanel" id="${id}-p${i}" aria-labelledby="${id}-t${i}" tabindex="0" ${i?'hidden':''}><span class="ov-serial">${String(i+1).padStart(2,'0')}</span><p>${e(p.panels?.[i]||['光线留下形状，观看赋予意义。','让一段旋律，打开一个世界。','形式是情绪留下的轮廓。'][i%3])}</p></div>`).join('')}</div>`);
    const tabs=[...root.querySelectorAll('[role=tab]')], panels=[...root.querySelectorAll('[role=tabpanel]')], line=root.querySelector('.ov-tabs__line');
    // The viewfinder is a sprung object: it stretches toward where it is going and settles with a small overshoot.
    const frame=M.spring({preset:'snap',value:0,precision:.0004,onUpdate:(x,v)=>{const stretch=Math.min(.28,Math.abs(v)*.022);line.style.transformOrigin=v<0?'100% 50%':'0 50%';line.style.transform=`translateX(${x*100}%) scaleX(${1+stretch})`;}});line.style.transition='none';
    const select=(n,focus=false)=>{const prev=current;current=(n+tabs.length)%tabs.length;root.dataset.dir=current<prev?'back':'fwd';tabs.forEach((tab,i)=>{tab.setAttribute('aria-selected',String(i===current));tab.tabIndex=i===current?0:-1;panels[i].hidden=i!==current;});root.style.setProperty('--tab',current);root.style.setProperty('--tabs',tabs.length);frame.to(current);if(prev!==current)S.play('tick',{at:tabs[current]});if(focus)tabs[current].focus();c.emit({index:current,value:values[current]});};
    tabs.forEach((b,i)=>{c.listen(b,'click',()=>select(i));c.listen(b,'keydown',ev=>{let n=ev.key==='ArrowRight'?current+1:ev.key==='ArrowLeft'?current-1:ev.key==='Home'?0:ev.key==='End'?tabs.length-1:null;if(n!==null){ev.preventDefault();select(n,true);}});});c.cleanup(()=>frame.stop());c.setValue=n=>select(+n||0);select(0);frame.set(0);return root;
  });
  O.define('ChapterNav',(p,c)=>{const items=p.items||['序曲','观看','共鸣'];const root=html(`<nav class="ov-chapters" aria-label="章节">${items.map((x,i)=>`<button type="button" aria-current="${i===0?'step':'false'}"><span>${String(i+1).padStart(2,'0')}</span>${e(x)}</button>`).join('')}</nav>`);[...root.children].forEach((b,i)=>c.listen(b,'click',()=>{const prev=[...root.children].findIndex(x=>x.getAttribute('aria-current')==='step');root.dataset.dir=i<prev?'back':'fwd';[...root.children].forEach(x=>x.setAttribute('aria-current','false'));b.setAttribute('aria-current','step');if(prev!==i)S.play('tick',{at:b});c.emit({index:i});p.onSelect?.(i);}));return root;});
  O.define('Breadcrumb',(p,c)=>{const root=html(`<nav class="ov-breadcrumb" aria-label="路径">${(p.items||['作品','舞台','幕间']).map((v,i,a)=>i===a.length-1?`<span aria-current="page">${e(v)}</span>`:`<a href="#">${e(v)}</a>${icon('next')}`).join('')}</nav>`);root.querySelectorAll('a').forEach(a=>c.listen(a,'click',ev=>{ev.preventDefault();c.emit({value:a.textContent});}));return root;});
  O.define('Pagination',(p,c)=>{let page=1;const total=p.total||36,size=p.size||6;const root=html(`<nav class="ov-pagination" aria-label="翻页"><button class="ov-icon-button" aria-label="上一页">${icon('back')}</button><span aria-live="polite"></span><button class="ov-icon-button" aria-label="下一页">${icon('next')}</button></nav>`),bs=root.querySelectorAll('button'),label=root.querySelector('span');const update=(v,touched)=>{const s=O.model.page(v,total,size),dir=Math.sign(s.page-page)||1;page=s.page;bs[0].disabled=page===1;bs[1].disabled=page===s.pages;M.count(label,`${String(page).padStart(2,'0')} / ${String(s.pages).padStart(2,'0')}`,dir);if(touched)S.play('tick',{at:label});c.emit(s);};c.listen(bs[0],'click',()=>update(page-1,true));c.listen(bs[1],'click',()=>update(page+1,true));c.setValue=update;update(page);return root;});
  O.define('TextField',(p,c)=>{
    const id=O.uid('field');const root=html(`<label class="ov-field" for="${id}"><span>${e(p.label||'电子邮箱')}</span><span class="ov-field__control"><input id="${id}" type="${e(p.type||'email')}" placeholder="${e(p.placeholder||'name@example.com')}" value="${e(p.value||'')}" aria-describedby="${id}-help" ${p.required?'required':''} ${p.disabled?'disabled':''}>${icon('frame')}</span><small id="${id}-help" aria-live="polite">${e(p.help||'收到新作时，再与你相见。')}</small></label>`),input=root.querySelector('input'),help=root.querySelector('small');
    // A new error is exposed onto the line: the proof-red rule runs under the field and the message develops in.
    const validate=()=>{const invalid=(input.value.length>0||p.required)&&!input.checkValidity(),was=input.getAttribute('aria-invalid')==='true';input.setAttribute('aria-invalid',String(invalid));help.textContent=invalid?(p.error||'请填写完整的邮箱地址。'):(p.help||'收到新作时，再与你相见。');if(invalid!==was)M.develop(help,{duration:520});c.emit({value:input.value,valid:!invalid});return !invalid;};c.listen(input,'blur',validate);c.listen(input,'input',()=>{if(input.getAttribute('aria-invalid')==='true')validate();else c.emit({value:input.value,valid:input.checkValidity()});});c.setValue=v=>{input.value=String(v);validate();};return root;
  });
  O.define('TextArea',(p,c)=>{const id=O.uid('text');const max=p.maxLength||180;const root=html(`<label class="ov-field"><span>${e(p.label||'创作笔记')}</span><textarea id="${id}" rows="4" maxlength="${max}" placeholder="${e(p.placeholder||'写下一瞬间的感受……')}" aria-describedby="${id}-count">${e(p.value||'')}</textarea><small id="${id}-count" aria-live="polite">0 / ${max}</small></label>`),input=root.querySelector('textarea'),out=root.querySelector('small');const update=()=>{out.textContent=`${input.value.length} / ${max}`;root.classList.toggle('is-near-limit',input.value.length>=max*.9);c.emit({value:input.value,remaining:max-input.value.length});};c.listen(input,'input',update);c.setValue=v=>{input.value=String(v).slice(0,max);update();};update();return root;});
  O.define('Select',(p,c)=>{const values=p.items||['摄影作品集','演出节目单','时装企划'];const root=html(`<label class="ov-field"><span>${e(p.label||'制作类型')}</span><span class="ov-select"><select>${values.map(v=>`<option>${e(v)}</option>`).join('')}</select>${icon('chevron')}</span></label>`),input=root.querySelector('select');c.listen(input,'change',()=>{S.play('tick',{at:input});c.emit({value:input.value});});c.setValue=v=>{input.value=v;c.emit({value:input.value});};return root;});
  O.define('ChoiceGroup',(p,c)=>{const id=O.uid('choice'),items=p.items||['暗场 Stage','印纸 Paper','朱红 Accent'];const root=html(`<fieldset class="ov-choices"><legend>${e(p.label||'画面的情绪')}</legend>${items.map((v,i)=>`<label><input type="radio" name="${id}" value="${e(v)}" ${i===0?'checked':''}><span>${e(v)}</span></label>`).join('')}</fieldset>`);root.querySelectorAll('input').forEach((input,i)=>c.listen(input,'change',()=>{S.play('tick',{at:input.parentElement});c.emit({index:i,value:input.value});}));return root;});
  O.define('Check',(p,c)=>{const root=html(`<label class="ov-check"><input type="checkbox" ${p.value?'checked':''} ${p.disabled?'disabled':''}><span class="ov-check__box">${icon('check')}</span><span>${e(p.label||'把这一帧加入精选')}</span></label>`),input=root.querySelector('input');c.listen(input,'change',()=>{S.play('tick',{at:root,pitch:input.checked?1.15:.85});c.emit({value:input.checked});});c.setValue=v=>{input.checked=!!v;c.emit({value:!!v});};return root;});
  O.define('Switch',(p,c)=>{const root=html(`<button type="button" class="ov-switch" role="switch" aria-checked="${!!p.value}" ${p.disabled?'disabled':''}><span class="ov-switch__track" aria-hidden="true"><i></i></span><span>${e(p.label||'显示取景标记')}</span></button>`);const set=v=>{root.setAttribute('aria-checked',String(!!v));c.emit({value:!!v});};c.listen(root,'click',()=>{S.play('lever',{at:root});set(root.getAttribute('aria-checked')!=='true');});c.setValue=set;return root;});
  O.define('Range',(p,c)=>{
    const id=O.uid('range'),min=p.min??0,max=p.max??100,step=p.step??1;const root=html(`<label class="ov-range" for="${id}"><span>${e(p.label||'曝光 / Exposure')}</span><output for="${id}"></output><span class="ov-range__ruler" aria-hidden="true"><span class="ov-range__ticks">${Array.from({length:21},(_,i)=>`<i>${i%5===0?`<small>${+(min+(max-min)*i/20).toFixed(1)}</small>`:''}</i>`).join('')}</span><i class="ov-range__needle"></i></span><input id="${id}" type="range" min="${min}" max="${max}" step="${step}" value="${p.value??42}"><span class="ov-range__ends"><span>${e(p.minLabel||'收光')}</span><span>${e(p.maxLabel||'放光')}</span></span></label>`),input=root.querySelector('input'),out=root.querySelector('output');
    // The needle is a meter needle: it trails the thumb and settles with a slight overshoot. The number is always exact.
    const pct=v=>max===min?0:(v-min)/(max-min)*100;let tick=Math.round(pct(+input.value)/5);
    const needle=M.spring({preset:'snap',value:pct(O.model.range(input.value,min,max,step)),precision:.02,onUpdate:x=>root.style.setProperty('--needle',`${x}%`)});c.cleanup(()=>needle.stop());
    const update=(v,touched)=>{const value=O.model.range(v,min,max,step),at=pct(value);input.value=value;out.textContent=`${value}${p.unit||''}`;root.style.setProperty('--exposure',`${at}%`);needle.to(at);const t=Math.round(at/5);if(touched&&t!==tick)S.play('tick',{at:root,pitch:t%5===0?1.25:1,gain:t%5===0?1:.6});tick=t;input.setAttribute('aria-valuetext',`${value}${p.unit||''}`);c.emit({value});};
    c.listen(input,'input',()=>update(input.value,true));c.setValue=update;update(input.value);needle.set(pct(+input.value));return root;
  });
  O.define('Stepper',(p,c)=>{let value=p.value??3,min=p.min??1,max=p.max??12;const root=html(`<div class="ov-stepper"><span>${e(p.label||'印刷份数')}</span><div><button class="ov-icon-button" aria-label="减少">${icon('minus')}</button><output aria-live="polite"></output><button class="ov-icon-button" aria-label="增加">${icon('plus')}</button></div></div>`),b=root.querySelectorAll('button'),out=root.querySelector('output');const set=(v,touched)=>{const next=O.model.range(v,min,max,1),dir=Math.sign(next-value)||1;value=next;M.count(out,String(value).padStart(2,'0'),dir);if(touched)S.play('tick',{at:out});b[0].disabled=value===min;b[1].disabled=value===max;c.emit({value});};c.listen(b[0],'click',()=>set(value-1,true));c.listen(b[1],'click',()=>set(value+1,true));c.setValue=set;set(value);return root;});
  O.define('TagInput',(p,c)=>{
    let tags=O.model.tags(p.value||['舞台','逆光']);const root=html(`<div class="ov-field"><label for="${O.uid('tag')}">${e(p.label||'作品关键词')}</label><div class="ov-tag-input"><span></span><input aria-label="添加关键词" placeholder="输入后按 Enter" maxlength="24"></div><small>Enter 添加，Backspace 移除最后一项；最多 12 项。</small></div>`),input=root.querySelector('input'),list=root.querySelector('.ov-tag-input>span');root.querySelector('label').htmlFor=input.id=O.uid('tag-input');
    // Tags keep their identity: survivors slide to their new places, a new one develops in, a removed one is cut away.
    const draw=()=>{list.replaceChildren(...tags.map(v=>{const b=html(`<button type="button" class="ov-tag" data-key="${e(v)}" aria-label="移除 ${e(v)}">${e(v)}${icon('close')}</button>`);b.addEventListener('click',()=>remove(v,true));return b;}));};
    const update=()=>{M.flip(root.querySelector('.ov-tag-input'),'.ov-tag',draw);c.emit({value:[...tags]});};
    function remove(v,refocus){const b=[...list.children].find(x=>x.dataset.key===v);if(!b||b.dataset.leaving)return;b.dataset.leaving='1';S.play('tick',{at:b,pitch:.8});const done=()=>{tags=tags.filter(t=>t!==v);update();if(refocus)input.focus();};if(O.reduced()||!b.animate){done();return;}b.style.pointerEvents='none';b.animate([{clipPath:'inset(0 0 0 0)',opacity:1},{clipPath:'inset(0 100% 0 0)',opacity:0}],{duration:200,easing:M.exit,fill:'forwards'}).finished.then(done,done);}
    c.listen(input,'keydown',ev=>{if(ev.key==='Enter'||ev.key===','){ev.preventDefault();const before=tags.length;tags=O.model.tags([...tags,input.value]);input.value='';if(tags.length>before)S.play('tick',{at:input,pitch:1.15});update();}else if(ev.key==='Backspace'&&!input.value&&tags.length){remove(tags[tags.length-1]);}});c.setValue=v=>{tags=O.model.tags(v);update();};draw();c.emit({value:[...tags]});return root;
  });
  O.define('Dropzone',(p,c)=>{let url;const root=html(`<div class="ov-drop"><label class="ov-drop__target" tabindex="0">${icon('upload')}<strong>把照片放入取景框</strong><span>或选择本地文件</span><input type="file" accept="image/png,image/jpeg,image/webp"></label><p class="ov-help" role="status">PNG / JPEG / WebP · 最大 10 MB · 仅本机预览</p><img hidden alt="所选图片预览"></div>`),target=root.querySelector('label'),input=root.querySelector('input'),status=root.querySelector('p'),img=root.querySelector('img');const select=file=>{const error=O.model.file(file);if(error){status.textContent=error;status.classList.add('is-error');M.develop(status,{duration:480});c.emit({error});return;}if(url)URL.revokeObjectURL(url);url=URL.createObjectURL(file);img.src=url;img.hidden=false;S.play('drop',{at:target});Promise.resolve(img.decode?.()).catch(()=>{}).then(()=>M.develop(img,{duration:900}));status.textContent=file.name;status.classList.remove('is-error');c.emit({fileName:file.name,size:file.size});};c.listen(input,'change',()=>{if(input.files[0])select(input.files[0]);});c.listen(target,'keydown',ev=>{if(ev.key==='Enter'||ev.key===' '){ev.preventDefault();input.click();}});['dragenter','dragover'].forEach(event=>c.listen(target,event,ev=>{ev.preventDefault();target.classList.add('is-dragging');}));['dragleave','drop'].forEach(event=>c.listen(target,event,ev=>{ev.preventDefault();target.classList.remove('is-dragging');if(event==='drop')select(ev.dataTransfer.files[0]);}));c.cleanup(()=>{if(url)URL.revokeObjectURL(url);});return root;});
})(globalThis.Overture);
