(function(O){
  'use strict';
  const e=O.escape,icon=O.icon,html=O.html,M=O.motion,S=O.sound;
  let gpuModule;
  // A single-file build injects its own loader (the engine and three.js arrive as inline modules).
  function loadGPU(){return gpuModule??=(O.config.loadEngine?O.config.loadEngine():import(O.asset('engine.mjs')));}
  const photos=[['hero-backstage.jpg','幕间','PHOTOGRAPHY'],['stage-bow.jpg','谢幕','OPERA'],['red-silk.png','形与色','FASHION'],['runway.jpg','行走的光','FASHION'],['camera-hands.jpg','观看','PHOTOGRAPHY'],['backstage-mirror.jpg','镜中','OPERA']];
  O.photos=photos;
  function photo(v){return O.asset('photos/'+v);}
  function hookGPU(host,p,c){
    let engine=null,latest=p.value??.55,pointer=[.5,.5];
    const api={setValue(v){latest=v;engine?.setValue(v);},setPointer(x,y){pointer=[x,y];engine?.setPointer(x,y);},setActive(v){engine?.setActive(v);},setHover(v){engine?.setHover?.(v);},setOrigin(x,y){engine?.setOrigin?.(x,y);},setIris(v){engine?.setIris?.(v);},setBeam(x,y,v,k=1){pointer=[x,y];latest=v;if(engine?.setBeam)engine.setBeam(x,y,v,k);else if(engine){engine.setIris?.(k);engine.setValue(v);engine.setPointer(x,y);}},setPaused(v){engine?.setPaused(v);},capture(){return engine?.capture()||Promise.reject(new Error('画面还未就绪'));},get state(){return engine?.state||{backend:'loading'};},get engine(){return engine;}};
    loadGPU().then(async mod=>{if(!c.alive)return;engine=await mod.mountGPU(host,{...p,value:latest,backend:O.config.backend,onController:ctrl=>{engine=ctrl;ctrl.setPointer(...pointer);c.cleanup(()=>ctrl.destroy());},onBackend:backend=>{host.dataset.renderer=backend;c.emit({backend});}});if(!c.alive)engine.destroy();}).catch(err=>{host.dataset.renderer='static';host.dataset.gpuError=err.message;});
    host.ovGPU=api;return api;
  }
  O.gpu={mount:hookGPU,load:loadGPU};
  const local=(ev,el)=>{const r=el.getBoundingClientRect();return [(ev.clientX-r.left)/Math.max(1,r.width),(ev.clientY-r.top)/Math.max(1,r.height)];};
  O.define('ApertureStage',(p,c)=>{
    const root=html(`<div class="ov-aperture"><div class="ov-gpu ov-aperture__scene"><img class="ov-gpu-fallback" src="${photo('overture-art.png')}" alt="丝绸光圈中的歌剧舞台"></div>${p.chrome===false?'':`<div class="ov-aperture__caption"><span>Light. Emotion. Form.</span><button type="button" class="ov-button ov-button--circle"><span>ENTER</span></button></div><label class="ov-aperture__scrub"><span>开幕</span><input aria-label="光圈开度" type="range" min="0" max="100" value="74"><span>进入</span></label>`}</div>`);
    const scene=root.querySelector('.ov-gpu'),gpu=hookGPU(scene,{type:'aperture',src:photo('overture-art.png'),value:.74},c);root.ovGPU=gpu;
    // The aperture has mass: ENTER opens it over the stage spring; the ring and scroll follow it without snapping.
    const opening=M.spring({preset:'stage',value:.74,precision:.0004,onUpdate:v=>gpu.setValue(v)}),look=M.spring({preset:'settle',value:[.5,.5],precision:.0005,onUpdate:([x,y])=>gpu.setPointer(x,y)});c.cleanup(()=>{opening.stop();look.stop();});
    c.listen(scene,'pointermove',ev=>look.to(local(ev,scene)));c.listen(scene,'pointerleave',()=>look.to([.5,.5]));
    const slider=root.querySelector('input');if(slider)c.listen(slider,'input',()=>{opening.to(+slider.value/100,{preset:'snap'});c.emit({value:+slider.value});});
    const b=root.querySelector('button');if(b)c.listen(b,'click',()=>{const open=b.dataset.open!=='true';b.dataset.open=open;opening.to(open?1:.35,{preset:'stage'});S.play('iris',{at:b});slider.value=open?100:35;b.querySelector('span').textContent=open?'RETURN':'ENTER';c.emit({open});});
    c.setValue=v=>{opening.to(+v/100,{preset:'settle'});if(slider)slider.value=v;};root.ovAperture=opening;return root;
  });
  O.define('DevelopImage',(p,c)=>{const src=p.src||photo('red-silk.png');const root=html(`<button type="button" class="ov-develop" aria-label="${e(p.label||'显影并选择照片')}" aria-pressed="false"><span class="ov-gpu"><img class="ov-gpu-fallback" src="${e(src)}" alt="${e(p.alt||'红色褶皱时装摄影')}"></span><span class="ov-focus-corners"></span><span class="ov-image-caption">${e(p.caption||'FORM / 003')}</span></button>`),scene=root.querySelector('.ov-gpu'),gpu=hookGPU(scene,{type:'develop',src},c);let chosen=false,inside=false,last=[.5,.5];
    // The pool of developer trails the pointer, grows in on arrival and shrinks away on exit;
    // choosing floods the whole frame from the point that was pressed.
    const follow=M.spring({preset:'settle',value:[.5,.5],precision:.0005,onUpdate:([x,y])=>gpu.setPointer(x,y)}),pool=M.spring({preset:'settle',value:0,precision:.001,onUpdate:v=>gpu.setHover(v)}),flood=M.spring({preset:'stage',value:0,precision:.0008,onUpdate:v=>gpu.setActive(v)});c.cleanup(()=>[follow,pool,flood].forEach(s=>s.stop()));
    c.listen(root,'pointermove',ev=>{last=local(ev,root);if(!inside){inside=true;follow.set(last);}else follow.to(last);pool.to(1);});
    c.listen(root,'pointerleave',()=>{inside=false;pool.to(0);});
    c.listen(root,'focus',()=>{if(!root.matches(':focus-visible'))return;gpu.setOrigin(.5,.5);flood.to(1);});c.listen(root,'blur',()=>flood.to(chosen?1:0));
    c.listen(root,'click',ev=>{chosen=!chosen;root.setAttribute('aria-pressed',String(chosen));const at=ev.detail?last:[.5,.5];gpu.setOrigin(...at);flood.to(chosen?1:0);S.play('paper',{at:root,pitch:chosen?1:.8});c.emit({value:chosen});});return root;
  });
  O.define('CompareLens',(p,c)=>{const src=p.src||photo('red-silk.png');const id=O.uid('compare');const root=html(`<div class="ov-compare" style="--split:50%"><img src="${e(src)}" alt="黑白版本" class="ov-compare__base"><div class="ov-compare__color"><img src="${e(src)}" alt="彩色版本"></div><span class="ov-compare__line">${icon('frame')}</span><span class="ov-compare__label">MONOCHROME</span><span class="ov-compare__label ov-compare__label--right">DEVELOPED</span><input id="${id}" type="range" min="0" max="100" value="50" aria-label="黑白与彩色比较分界"></div>`),input=root.querySelector('input');const edge=M.spring({preset:'snap',value:50,precision:.02,onUpdate:v=>root.style.setProperty('--split',`${v}%`)});c.cleanup(()=>edge.stop());const set=v=>{input.value=O.model.clamp(v,0,100);edge.to(+input.value);input.setAttribute('aria-valuetext',`彩色区域 ${input.value}%`);c.emit({value:+input.value});};c.listen(input,'input',()=>set(input.value));c.setValue=set;return root;});
  O.define('FocusGallery',(p,c)=>{
    const items=p.items||photos.slice(0,4);let index=0,from=null,leaving=null;const id=O.uid('gallery');const root=html(`<div class="ov-gallery"><div class="ov-gallery__grid">${items.map((v,i)=>`<button type="button" aria-label="放大 ${e(v[1])}"><img src="${photo(v[0])}" alt="${e(v[1])}"><span class="ov-focus-corners"></span><span>${e(v[1])}</span></button>`).join('')}</div><dialog class="ov-lightbox" aria-label="照片查看器"><button type="button" class="ov-icon-button ov-dialog__close" aria-label="关闭照片">${icon('close')}</button><button type="button" class="ov-icon-button ov-lightbox__previous" aria-label="上一张">${icon('back')}</button><figure><img alt=""><figcaption aria-live="polite"></figcaption></figure><button type="button" class="ov-icon-button ov-lightbox__next" aria-label="下一张">${icon('next')}</button></dialog></div>`),dialog=root.querySelector('dialog'),thumbs=[...root.querySelectorAll('.ov-gallery__grid>button')],big=dialog.querySelector('figure img');
    const show=(n,dir=0)=>{index=(n+items.length)%items.length;big.src=photo(items[index][0]);big.alt=items[index][1];dialog.querySelector('figcaption').textContent=`${items[index][1]} · ${index+1} / ${items.length}`;if(dir&&!O.reduced()){big.animate([{transform:`translateX(${dir*48}px)`,opacity:0},{transform:'translateX(0)',opacity:1}],{duration:M.time('settle'),easing:M.easing('settle')});M.develop(big,{duration:760,from:'gray'});S.play('paper',{at:big,pitch:dir>0?1.05:.95});}c.emit({index});};
    // The print leaves the sheet and flies to the light table; closing flies it back to its place.
    const fitted=()=>{const box=big.getBoundingClientRect(),ratio=(big.naturalWidth/big.naturalHeight)||box.width/Math.max(1,box.height);let w=box.width,h=w/ratio;if(h>box.height){h=box.height;w=h*ratio;}return {left:box.left+(box.width-w)/2,top:box.top+(box.height-h)/2,width:w,height:h};};
    function fly(a,b,reverse){if(O.reduced()||!a||!b.width)return Promise.resolve();const proxy=document.createElement('img');proxy.src=big.src;proxy.alt='';proxy.className='ov-flight';dialog.append(proxy);big.style.opacity='0';const box=r=>({left:`${r.left}px`,top:`${r.top}px`,width:`${r.width}px`,height:`${r.height}px`});const frames=[{...box(a),filter:'grayscale(1)'},{...box(b),filter:'grayscale(0)'}];if(reverse)frames.reverse();return proxy.animate(frames,{duration:reverse?360:M.time('stage'),easing:reverse?M.exit:M.easing('settle'),fill:'forwards'}).finished.catch(()=>{}).then(()=>{proxy.remove();big.style.opacity='';});}
    async function open(i){from=thumbs[i];show(i);leaving=null;dialog.classList.remove('is-closing');if(!O.reduced())big.style.opacity='0';if(!dialog.open)dialog.showModal();S.play('paper',{at:from});if(O.reduced())return;await Promise.resolve(big.decode?.()).catch(()=>{});if(dialog.open&&!leaving)await fly(from.querySelector('img').getBoundingClientRect(),fitted(),false);big.style.opacity='';}
    function close(){if(!dialog.open||leaving)return leaving;const back=thumbs[index],r=back.querySelector('img').getBoundingClientRect(),visible=r.bottom>0&&r.top<innerHeight;dialog.classList.add('is-closing');S.play('paper',{at:back,pitch:.8});leaving=(visible?fly(r,fitted(),true):Promise.resolve()).then(()=>{if(!leaving)return;leaving=null;dialog.classList.remove('is-closing');if(dialog.open)dialog.close();});return leaving;}
    thumbs.forEach((b,i)=>c.listen(b,'click',()=>open(i)));c.listen(dialog.querySelector('.ov-dialog__close'),'click',close);c.listen(dialog.querySelector('.ov-lightbox__previous'),'click',()=>show(index-1,-1));c.listen(dialog.querySelector('.ov-lightbox__next'),'click',()=>show(index+1,1));c.listen(dialog,'keydown',ev=>{if(ev.key==='ArrowRight')show(index+1,1);if(ev.key==='ArrowLeft')show(index-1,-1);});c.listen(dialog,'cancel',ev=>{ev.preventDefault();close();});c.listen(dialog,'click',ev=>{if(ev.target===dialog)close();});c.listen(dialog,'close',()=>{leaving=null;dialog.classList.remove('is-closing');big.style.opacity='';dialog.querySelectorAll('.ov-flight').forEach(x=>x.remove());});c.cleanup(()=>{if(dialog.open)dialog.close();});return root;
  });
  O.define('SilkResonance',(p,c)=>{
    let value=p.value??56,paused=false,drag;
    const root=html(`<div class="ov-silk"><div class="ov-gpu ov-silk__scene" tabindex="0" role="slider" aria-label="丝绸张力，左右方向键调整" aria-valuemin="0" aria-valuemax="100" aria-valuenow="${value}"><img class="ov-silk-fallback" src="${photo('resonance-silk.png')}" alt="象牙色半透明褶皱丝绸与红色缝线"><span class="ov-focus-corners"></span><span class="ov-silk-loupe" aria-hidden="true"><img src="${photo('resonance-silk.png')}" alt=""><i></i></span></div>${p.chrome===false?'':`<div class="ov-silk__controls"><label>张力 <output>${value}</output><input type="range" min="0" max="100" value="${value}" aria-label="褶皱张力"></label><button class="ov-icon-button" aria-label="凝住这一瞬" aria-pressed="false">${icon('pause')}</button><button class="ov-icon-button" aria-label="下载雕塑图片">${icon('download')}</button></div><p class="ov-help" role="status">拖动衣料后松手，它会按张力回荡 · 凝住会停在回荡中途</p>`}</div>`),scene=root.querySelector('.ov-gpu'),gpu=hookGPU(scene,{type:'silk',src:photo('resonance-silk.png'),value:value/100},c);root.ovGPU=gpu;
    // Tension is a lightly damped spring: a release carries its velocity past the new tension and rings out.
    // Freezing holds the exact displacement and velocity; thawing lets the same ring continue.
    const tension=M.spring({preset:'resonance',value:value/100,precision:.0004,onUpdate:v=>gpu.setValue(v)}),look=M.spring({preset:'settle',value:[.5,.5],precision:.0005,onUpdate:([x,y])=>gpu.setPointer(x,y)});c.cleanup(()=>{tension.stop();look.stop();});
    const slider=root.querySelector('input'),output=root.querySelector('output');const set=(n,o={})=>{value=O.model.clamp(n,0,100);tension.to(value/100,o);scene.setAttribute('aria-valuenow',String(Math.round(value)));if(slider)slider.value=value;if(output)output.value=Math.round(value);c.emit({value});};
    if(slider){c.listen(slider,'input',()=>set(+slider.value,{preset:'snap'}));c.listen(slider,'change',()=>set(+slider.value,{preset:'resonance'}));}
    c.listen(scene,'pointermove',ev=>{const [x,y]=local(ev,scene),r=scene.getBoundingClientRect();look.to([x,y]);scene.style.setProperty('--loupe-x',Math.max(10,Math.min(78,x*100))+'%');scene.style.setProperty('--loupe-y',Math.max(8,Math.min(58,y*100))+'%');if(drag){const now=performance.now(),next=drag.value+(ev.clientX-drag.x)/r.width*90;drag.v=drag.v*.5+((next-drag.last)/Math.max(8,now-drag.t))*500;drag.t=now;drag.last=next;set(next,{preset:'snap'});}});
    c.listen(scene,'pointerleave',()=>{if(!drag)look.to([.5,.5]);});
    c.listen(scene,'pointerdown',ev=>{if(ev.button!==0)return;drag={x:ev.clientX,value,last:value,t:performance.now(),v:0};scene.setPointerCapture(ev.pointerId);});
    ['pointerup','pointercancel'].forEach(n=>c.listen(scene,n,()=>{if(!drag)return;const v=drag.v;drag=null;tension.to(value/100,{preset:'resonance'});if(Math.abs(v)>20)S.play('silk',{at:scene,gain:Math.min(1.4,Math.abs(v)/160)});}));
    c.listen(scene,'keydown',ev=>{if(['ArrowLeft','ArrowDown','ArrowRight','ArrowUp','Home','End'].includes(ev.key)){ev.preventDefault();set(ev.key==='Home'?0:ev.key==='End'?100:value+(['ArrowRight','ArrowUp'].includes(ev.key)?5:-5),{preset:'resonance'});}});
    const bs=root.querySelectorAll('button');if(bs.length){c.listen(bs[0],'click',()=>{paused=!paused;tension.freeze(paused);gpu.setPaused(paused);S.play(paused?'shutter':'tick',{at:bs[0]});bs[0].setAttribute('aria-pressed',String(paused));bs[0].setAttribute('aria-label',paused?'继续共振':'凝住这一瞬');bs[0].innerHTML=icon(paused?'play':'pause');c.emit({paused});});c.listen(bs[1],'click',async()=>{try{const canvas=await gpu.capture();canvas.toBlob(blob=>{if(blob)O.download(blob,'overture-resonance.png');},'image/png');root.querySelector('.ov-help').textContent='这一瞬已导出。';}catch(err){root.querySelector('.ov-help').textContent=err.message;}});}
    c.setValue=v=>set(v,{preset:'resonance'});root.ovSilk={get tension(){return tension.value;},get target(){return tension.target;},get velocity(){return tension.velocity;},get frozen(){return tension.frozen;}};return root;
  });
  O.define('CuePlayer',(p,c)=>{
    let audio=null,playing=false,starting=false,started=0,elapsed=0,raf=0;const length=12;
    const root=html(`<div class="ov-player"><button class="ov-button ov-button--circle" aria-label="播放合成音色示意">${icon('play')}</button><div><span>ÉTUDE / FOR SILK</span><p>三音共振 · 合成音色示意</p><input type="range" min="0" max="12" step=".1" value="0" aria-label="播放位置"><output>00:00 / 00:12</output></div><button class="ov-icon-button" aria-label="静音" aria-pressed="false">${icon('sound')}</button></div>`),bs=root.querySelectorAll('button'),range=root.querySelector('input'),out=root.querySelector('output');let muted=false;
    function stop(){playing=false;starting=false;cancelAnimationFrame(raf);if(audio){if(audio.state!=='closed')audio.close().catch(()=>{});audio=null;}root.ovGain=null;bs[0].innerHTML=icon('play');bs[0].setAttribute('aria-label','播放合成音色示意');c.emit({playing:false});}
    async function play(){if(starting)return;if(playing){stop();return;}starting=true;try{const Audio=window.AudioContext||window.webkitAudioContext;const context=new Audio();audio=context;await context.resume();if(!c.alive||audio!==context){if(context.state!=='closed')await context.close();return;}const gain=context.createGain();gain.gain.value=muted?0:.045;gain.connect(context.destination);root.ovGain=gain;[220,329.63,440].forEach((f,i)=>{const osc=context.createOscillator(),env=context.createGain();osc.type='sine';osc.frequency.value=f;env.gain.value=.7/(i+1);osc.connect(env).connect(gain);osc.start();});starting=false;playing=true;started=performance.now()-elapsed*1000;bs[0].innerHTML=icon('pause');bs[0].setAttribute('aria-label','暂停合成音色');c.emit({playing:true});function tick(){if(!playing)return;elapsed=(performance.now()-started)/1000;range.value=elapsed;out.value=`00:${String(Math.floor(elapsed)).padStart(2,'0')} / 00:12`;if(elapsed>=length){elapsed=0;range.value=0;out.value='00:00 / 00:12';stop();}else raf=requestAnimationFrame(tick);}raf=requestAnimationFrame(tick);}catch{out.value='此浏览器无法播放合成音色。';stop();}}
    c.listen(bs[0],'click',play);c.listen(bs[1],'click',()=>{muted=!muted;bs[1].setAttribute('aria-pressed',String(muted));bs[1].setAttribute('aria-label',muted?'取消静音':'静音');root.ovGain?.gain.setTargetAtTime(muted?0:.045,audio?.currentTime||0,.08);});c.listen(range,'input',()=>{elapsed=+range.value;started=performance.now()-elapsed*1000;out.value=`00:${String(Math.floor(elapsed)).padStart(2,'0')} / 00:12`;c.emit({position:elapsed});});c.cleanup(stop);return root;
  });
})(globalThis.Overture);
