(function(O){
  'use strict';const e=O.escape,icon=O.icon,html=O.html,M=O.motion,S=O.sound;
  const trigger=(label)=>`<button type="button" class="ov-button"><span>${e(label)}</span>${icon('arrow')}</button>`;
  O.define('Accordion',(p,c)=>{const items=p.items||[['把光线当作材料','不要为每个组件添加一束光。让聚焦、显影和选择各自有明确用途。'],['让状态可以被看见','选择用红色取景角锁定；确认用文字与完成标记一起表达。'],['给作品留下呼吸','大字、真实图像、少量细线。密集的操作界面也保留清楚的层级。']];const root=html(`<div class="ov-accordion">${items.map((v,i)=>`<details ${i===0?'open':''}><summary>${e(v[0])}${icon('plus')}</summary><p>${e(v[1])}</p></details>`).join('')}</div>`);root.querySelectorAll('details').forEach((d,i)=>{c.listen(d.querySelector('summary'),'click',()=>S.play('paper',{at:d,pitch:d.open?.85:1}));c.listen(d,'toggle',()=>c.emit({index:i,open:d.open}));});return root;});
  // Modal surfaces open from the control that asked for them and close back into it,
  // whichever way they are dismissed (button, cancel, Escape, backdrop, save).
  function modal(dialog,opener,c,{shape='circle',drawer=false,onClose}={}){
    let closing=null;
    const open=()=>{if(dialog.open&&!closing)return;closing=null;dialog.getAnimations().forEach(a=>{if(a.id!=='ov-iris')a.cancel();});dialog.classList.remove('is-closing');if(!dialog.open)dialog.showModal();S.play('paper',{at:opener});
      if(drawer){if(!O.reduced()){dialog.animate([{transform:'translateX(100%)'},{transform:'translateX(0)'}],{duration:M.time('settle'),easing:M.easing('settle')});[...dialog.children].forEach((el,i)=>el.animate([{transform:'translateX(56px)',opacity:0},{transform:'translateX(0)',opacity:1}],{duration:560,delay:90+i*45,easing:M.ease,fill:'backwards'}));}}
      else M.iris(dialog,{origin:opener,shape,duration:540});};
    const close=()=>{if(!dialog.open)return Promise.resolve();if(closing)return closing;dialog.classList.add('is-closing');S.play('paper',{at:opener,pitch:.8});
      const motion=O.reduced()?Promise.resolve():drawer?dialog.animate([{transform:'translateX(0)'},{transform:'translateX(100%)'}],{duration:280,easing:M.exit,fill:'forwards'}).finished.catch(()=>{}):M.iris(dialog,{open:false,origin:opener,shape,duration:300});
      closing=motion.then(()=>{if(!closing)return;closing=null;dialog.classList.remove('is-closing');if(dialog.open)dialog.close();M.release(dialog);dialog.getAnimations().forEach(a=>a.cancel());});return closing;};
    c.listen(dialog,'cancel',ev=>{ev.preventDefault();close();});
    c.listen(dialog,'click',ev=>{if(ev.target!==dialog)return;const r=dialog.getBoundingClientRect();if(ev.clientX<r.left||ev.clientX>r.right||ev.clientY<r.top||ev.clientY>r.bottom)close();});
    c.listen(dialog,'close',()=>{closing=null;dialog.classList.remove('is-closing');onClose?.();});
    c.cleanup(()=>{if(dialog.open)dialog.close();});
    return {open,close};
  }
  function overlay(p,c,drawer=false){
    const id=O.uid('dialog');const root=html(`<div class="ov-overlay-demo">${trigger(p.label||(drawer?'编辑画面说明':'保存这一幕'))}<p class="ov-help" role="status">${drawer?'侧边展开，保持当前作品的上下文。':'继续之前，确认这份创作的落款。'}</p><dialog class="ov-dialog ${drawer?'ov-drawer':''}" aria-labelledby="${id}"><button type="button" class="ov-icon-button ov-dialog__close" aria-label="关闭">${icon('close')}</button><h2 id="${id}">${e(p.title||(drawer?'Notes for the frame.':'Make it yours.'))}</h2><p>${drawer?'为这张作品补充一个标题和一句说明。内容只保留在当前页面。':'保存你为这一幕写下的标题。它会留在当前页面，供你继续调整。'}</p><label class="ov-field"><span>作品标题</span><input name="title" type="text" value="光的序曲" maxlength="60" required></label>${drawer?'<label class="ov-field"><span>画面说明</span><textarea name="note" rows="3" maxlength="180">在开幕前的一秒，让光先走进来。</textarea></label>':''}<div class="ov-dialog__actions"><button class="ov-button ov-button--solid" type="button" data-save>保存修改</button><button class="ov-text-link" type="button" data-cancel>取消</button></div></dialog></div>`),dialog=root.querySelector('dialog'),opener=root.firstElementChild,status=root.querySelector('.ov-help');
    const m=modal(dialog,opener,c,{drawer,onClose:()=>c.emit({open:false})});
    c.listen(opener,'click',()=>{m.open();c.emit({open:true});});root.querySelectorAll('[data-cancel],.ov-dialog__close').forEach(b=>c.listen(b,'click',()=>m.close()));
    c.listen(root.querySelector('[data-save]'),'click',()=>{const input=dialog.querySelector('input');if(!input.reportValidity())return;status.textContent=`已保存「${input.value}」`;M.develop(status,{duration:560,delay:220});c.emit({value:input.value,note:dialog.querySelector('textarea')?.value||'',saved:true});m.close();});return root;
  }
  O.define('Dialog',(p,c)=>overlay(p,c));O.define('Drawer',(p,c)=>overlay(p,c,true));
  O.define('Tooltip',(p,c)=>{const id=O.uid('tooltip');const root=html(`<div class="ov-tooltip-wrap"><button class="ov-icon-button" aria-label="查看取景说明" aria-describedby="${id}">${icon('frame')}</button><span id="${id}" role="tooltip" class="ov-tooltip">${e(p.text||'锁定选区，保留这一瞬。')}</span></div>`);c.listen(root,'keydown',ev=>{if(ev.key==='Escape')root.dataset.dismissed='true';});c.listen(root,'pointerleave',()=>delete root.dataset.dismissed);c.listen(root,'focusout',()=>delete root.dataset.dismissed);return root;});
  O.define('Popover',(p,c)=>{const id=O.uid('popover');const root=html(`<div class="ov-popover-demo"><button class="ov-button" type="button" aria-expanded="false" aria-controls="${id}"><span>取景选项</span>${icon('chevron')}</button><div class="ov-popover" id="${id}" hidden><h3>Frame settings</h3><label class="ov-check"><input type="checkbox" checked><span class="ov-check__box">${icon('check')}</span><span>显示取景边角</span></label><label class="ov-check"><input type="checkbox"><span class="ov-check__box">${icon('check')}</span><span>保持原始画幅</span></label></div></div>`),b=root.querySelector('button'),panel=root.querySelector('.ov-popover');
    // Opens from its trigger; closing folds back into it before the panel is hidden.
    const set=open=>{if(open===(b.getAttribute('aria-expanded')==='true'))return;b.setAttribute('aria-expanded',String(open));if(open){panel.hidden=false;M.iris(panel,{origin:b,duration:380});S.play('tick',{at:b});}else M.iris(panel,{open:false,origin:b,duration:220}).then(()=>{if(b.getAttribute('aria-expanded')==='false'){panel.hidden=true;M.release(panel);}});c.emit({open});};
    c.listen(b,'click',()=>set(b.getAttribute('aria-expanded')!=='true'));c.listen(document,'pointerdown',ev=>{if(!root.contains(ev.target))set(false);});c.listen(root,'keydown',ev=>{if(ev.key==='Escape'){set(false);b.focus();}});panel.querySelectorAll('input').forEach((input,i)=>c.listen(input,'change',()=>{S.play('tick',{at:input.parentElement});c.emit({option:i,value:input.checked});}));return root;});
  O.define('CommandPalette',(p,c)=>{const id=O.uid('command');const actions=p.actions||[{label:'打开摄影档案',value:'photography'},{label:'进入品牌工坊',value:'brand'},{label:'切换纸面主题',value:'paper'},{label:'调整共振强度',value:'resonance'},{label:'导出当前画面',value:'export'}];let filtered=actions,index=0;
    const root=html(`<div class="ov-overlay-demo">${trigger('寻找一个动作')}<p class="ov-help" role="status">搜索名称，方向键选择，Enter 执行。</p><dialog class="ov-dialog ov-command" aria-label="寻找动作"><label>${icon('search')}<input type="search" placeholder="想做些什么？" aria-label="搜索动作" aria-controls="${id}" autocomplete="off"><button class="ov-icon-button ov-dialog__close" aria-label="关闭搜索">${icon('close')}</button></label><div class="ov-command__list" id="${id}" role="listbox" aria-label="匹配动作"></div></dialog></div>`),dialog=root.querySelector('dialog'),input=root.querySelector('input'),list=root.querySelector('.ov-command__list'),opener=root.firstElementChild;
    const m=modal(dialog,opener,c,{shape:'circle'});
    function run(action){root.querySelector('.ov-help').textContent=`已选择：${action.label}`;M.develop(root.querySelector('.ov-help'),{duration:520,delay:200});c.emit({value:action.value});p.onSelect?.(action.value);m.close();}
    function draw(stagger){filtered=actions.filter(a=>a.label.toLowerCase().includes(input.value.trim().toLowerCase()));index=0;list.replaceChildren();if(!filtered.length){list.append(html('<p class="ov-command__empty">没有匹配动作。试试“摄影”或“品牌”。</p>'));input.removeAttribute('aria-activedescendant');return;}filtered.forEach((action,i)=>{const b=html(`<button type="button" role="option" id="${id}-${i}" aria-selected="${i===0}">${e(action.label)}${icon('arrow')}</button>`);b.addEventListener('click',()=>run(action));list.append(b);if(stagger&&!O.reduced()&&i<6)b.animate([{opacity:0,transform:'translateY(10px)'},{opacity:1,transform:'none'}],{duration:420,delay:120+i*32,easing:M.ease,fill:'backwards'});});input.setAttribute('aria-activedescendant',`${id}-0`);}
    const choose=n=>{index=n;list.querySelectorAll('button').forEach((b,i)=>b.setAttribute('aria-selected',String(i===index)));input.setAttribute('aria-activedescendant',`${id}-${index}`);S.play('tick',{at:list});};
    c.listen(opener,'click',()=>{input.value='';draw(true);m.open();input.focus();});c.listen(dialog.querySelector('button'),'click',()=>m.close());c.listen(input,'input',()=>draw(false));c.listen(input,'keydown',ev=>{if(!filtered.length)return;if(ev.key==='ArrowDown'||ev.key==='ArrowUp'){ev.preventDefault();choose((index+(ev.key==='ArrowDown'?1:-1)+filtered.length)%filtered.length);}if(ev.key==='Enter'){ev.preventDefault();run(filtered[index]);}});return root;
  });
  O.define('Toast',(p,c)=>{const root=html(`<div class="ov-toast-demo">${trigger('收藏这一帧')}<div class="ov-toast" role="status" hidden>${icon('check')}<span>已加入精选</span><button class="ov-text-link" type="button">撤销</button><button class="ov-icon-button" aria-label="关闭提示">${icon('close')}</button><i class="ov-toast__timer" aria-hidden="true"></i></div></div>`),toast=root.querySelector('.ov-toast'),label=toast.querySelector('span'),bar=toast.querySelector('.ov-toast__timer');
    // The exposure line under the message shows the time left; hovering or focusing pauses both.
    let timer=0,meter=null,left=0,since=0,held=false;
    const arm=ms=>{clearTimeout(timer);meter?.cancel();left=ms;since=performance.now();meter=bar.animate([{transform:'scaleX(1)'},{transform:'scaleX(0)'}],{duration:ms,fill:'forwards'});if(held)meter.pause();else timer=setTimeout(hide,ms);};
    function hold(on){if(on===held)return;held=on;if(!meter||toast.hidden)return;if(on){clearTimeout(timer);left=Math.max(0,left-(performance.now()-since));meter.pause();}else{since=performance.now();timer=setTimeout(hide,left);meter.play();}}
    function hide(){clearTimeout(timer);if(toast.hidden)return;M.iris(toast,{open:false,shape:'shutter',duration:240}).then(ok=>{if(ok===false&&!O.reduced())return;toast.hidden=true;held=false;M.release(toast);});}
    c.listen(root.firstElementChild,'click',()=>{const was=!toast.hidden;toast.hidden=false;M.count(label,'已加入精选',1);if(!was||toast.getAnimations().length){M.iris(toast,{shape:'shutter',duration:460});M.imprint(toast.querySelector('svg'));}S.play('tick',{at:toast,pitch:1.15});c.emit({saved:true});arm(6000);});
    const bs=toast.querySelectorAll('button');c.listen(bs[0],'click',()=>{M.count(label,'已撤销收藏',-1);S.play('tick',{at:toast,pitch:.85});c.emit({saved:false});arm(2200);});c.listen(bs[1],'click',hide);
    c.listen(toast,'pointerenter',()=>hold(true));c.listen(toast,'pointerleave',()=>{if(!toast.contains(document.activeElement))hold(false);});c.listen(toast,'focusin',()=>hold(true));c.listen(toast,'focusout',ev=>{if(!toast.contains(ev.relatedTarget)&&!toast.matches(':hover'))hold(false);});
    c.cleanup(()=>{clearTimeout(timer);meter?.cancel();});return root;});
  O.define('Notice',(p,c)=>{const root=html(`<div class="ov-notice" role="status">${icon('info')}<div><h3>${e(p.title||'照片尚未加入')}</h3><p>${e(p.message||'选择一张本地照片，即可完成这份作品。文件会留在你的设备上。')}</p><button class="ov-text-link" type="button">${e(p.action||'使用示例素材')}${icon('arrow')}</button></div></div>`);c.listen(root.querySelector('button'),'click',()=>{root.querySelector('h3').textContent='示例素材已就绪';root.querySelector('p').textContent='现在可以继续调整画面。';root.querySelector('button').disabled=true;root.classList.add('is-resolved');M.develop(root.querySelector('div'),{duration:620});S.play('tick',{at:root,pitch:1.15});c.emit({resolved:true});});return root;});
  O.define('Progress',(p,c)=>{let value=p.value??34,timer=null;const root=html(`<div class="ov-progress"><div class="ov-progress__labels"><span>显影进度</span><output>${value}%</output></div><div class="ov-progress__track" role="progressbar" aria-label="显影进度" aria-valuemin="0" aria-valuemax="100" aria-valuenow="${value}"><i class="ov-progress__fill"></i></div><div class="ov-progress__steps"><span>EXPOSE</span><span>DEVELOP</span><span>FIX</span></div><div class="ov-demo-actions"><button class="ov-button" type="button">开始显影</button><button class="ov-text-link" type="button">重置</button></div><p class="ov-help" aria-live="polite"></p></div>`),track=root.querySelector('[role=progressbar]'),fill=root.querySelector('i'),out=root.querySelector('output'),bs=root.querySelectorAll('button');
    // Steps of 4 % arrive as one continuous development: a settling spring carries the fill, a cold glint marks its edge while running.
    const bar=M.spring({preset:'settle',value:value/100,precision:.0004,onUpdate:x=>{fill.style.transform=`scaleX(${Math.max(0,x)})`;root.style.setProperty('--head',Math.max(0,Math.min(1,x)));}});c.cleanup(()=>bar.stop());
    const set=v=>{value=O.model.clamp(v,0,100);track.setAttribute('aria-valuenow',Math.round(value));out.value=`${Math.round(value)}%`;bar.to(value/100);c.emit({value});};
    const running=on=>{root.dataset.running=String(on);};
    c.listen(bs[0],'click',()=>{if(timer){clearInterval(timer);timer=null;running(false);bs[0].textContent='继续显影';return;}if(value>=100)set(0);bs[0].textContent='暂停';running(true);root.querySelector('.ov-help').textContent='正在显影示例画面';timer=setInterval(()=>{set(value+4);if(value>=100){clearInterval(timer);timer=null;running(false);bs[0].textContent='重新显影';root.querySelector('.ov-help').textContent='显影完成，可以继续创作。';S.play('tick',{at:track,pitch:1.2});}},160);});c.listen(bs[1],'click',()=>{clearInterval(timer);timer=null;running(false);bs[0].textContent='开始显影';root.querySelector('.ov-help').textContent='';set(0);});c.setValue=set;c.cleanup(()=>clearInterval(timer));set(value);bar.set(value/100);return root;});
  O.define('Loading',(p,c)=>html(`<div class="ov-loading" role="status" aria-label="${e(p.label||'正在准备作品')}"><div class="ov-loading__iris">${icon('aperture')}</div><div class="ov-loading__lines" aria-hidden="true"><i></i><i></i><i></i></div><span class="ov-help">${e(p.label||'正在准备作品')}</span></div>`));
  O.define('EmptyState',(p,c)=>{const root=html(`<div class="ov-empty">${icon('frame')}<h3>${e(p.title||'The first frame.')}</h3><p>${e(p.message||'这里还没有精选。先放入一张让你停下来的照片。')}</p>${trigger('添加示例照片')}</div>`);c.listen(root.querySelector('button'),'click',()=>{root.querySelector('h3').textContent='A beginning.';root.querySelector('p').textContent='第一张精选已加入。';const image=document.createElement('img');image.src=O.asset('photos/hero-backstage.jpg');image.alt='示例：幕间的逆光';image.style.marginTop='24px';root.append(image);S.play('drop',{at:root});Promise.resolve(image.decode?.()).catch(()=>{}).then(()=>{M.iris(image,{shape:'unfold',duration:620});M.develop(image,{duration:1100});});root.querySelector('button').disabled=true;c.emit({empty:false});});return root;});
  O.define('EditorialTable',(p,c)=>{let direction=1,sortKey='title';const rows=p.rows||[{title:'幕间',category:'摄影',frames:12,state:'精选'},{title:'最后一束光',category:'歌剧',frames:8,state:'整理中'},{title:'红色的速度',category:'时装',frames:24,state:'精选'},{title:'衣料的声音',category:'时装',frames:16,state:'草稿'}];const root=html(`<div class="ov-table-wrap"><table class="ov-table"><caption class="ov-help" style="text-align:left;padding-bottom:18px">作品档案 · 点击标题或帧数排序</caption><thead><tr><th scope="col" aria-sort="none"><button data-key="title">作品${icon('chevron')}</button></th><th scope="col">领域</th><th scope="col" aria-sort="none"><button data-key="frames">帧数${icon('chevron')}</button></th><th scope="col">状态</th></tr></thead><tbody></tbody></table></div>`),body=root.querySelector('tbody');
    // Rows are kept, not rebuilt, so a new order is a movement of the same prints.
    const trs=new Map(rows.map((r,i)=>{const tr=html(`<table><tbody><tr data-key="${i}"><td>${e(r.title)}</td><td>${e(r.category)}</td><td>${e(r.frames)}</td><td><span class="ov-status">${e(r.state)}</span></td></tr></tbody></table>`).querySelector('tr');return [r,tr];}));
    function render(animate){const apply=()=>{for(const r of O.model.sort(rows,sortKey,direction))body.append(trs.get(r));};if(animate)M.flip(body,'tr',apply);else apply();root.querySelectorAll('th[aria-sort]').forEach(th=>th.setAttribute('aria-sort',th.querySelector('button').dataset.key===sortKey?(direction===1?'ascending':'descending'):'none'));}
    root.querySelectorAll('th button').forEach(b=>c.listen(b,'click',()=>{direction=sortKey===b.dataset.key?-direction:1;sortKey=b.dataset.key;S.play('paper',{at:b});render(true);c.emit({key:sortKey,direction});}));render(false);return root;});
  O.define('Timeline',(p,c)=>{const items=p.items||[['19:00','进入剧场','让视线适应黑暗。'],['19:30','第一幕','随着光线，找到观看的位置。'],['20:15','幕间','把刚才的一瞬记录下来。']];return html(`<ol class="ov-timeline">${items.map(v=>`<li><time>${e(v[0])}</time><div><strong>${e(v[1])}</strong><p>${e(v[2])}</p></div></li>`).join('')}</ol>`);});
})(globalThis.Overture);
